### ISSUE TITLE
default_url_options isn't used for the menu entries in the header

### ISSUE THREAD

**Issue by joker-777** [activeadmin/activeadmin#2074]
We have the locale in the default_url_options so our urls look like this:

/en/... or /de/...

this locale parameter isn't used for creating the menu entries in the header and hence rails can't find the route.

**Comment by wpp** [comment]
Hi,

Hope I'm not missing something but I ran into this again despite 
following the guides [here](https://github.com/activeadmin/activeadmin/wiki/Specifying-locale).

Server is running and I'm on `localhost:3000/de/admin`.
But all generated urls are missing the locale:

- `http://localhost:3000/superuser/users/78609/edit` instead of
- `http://localhost:3000/de/superuser/users/78609/edit`

### ApplicationController

      def default_url_options(options={})
        { locale: I18n.locale }.merge options
      end

Am I missing something?

**Comment by wpp** [comment]
Sorry I didn't realise there was [another guide](https://github.com/activeadmin/activeadmin/wiki/Switching-locale). Which addresses the behaviour:

> Anyway you will notice that all links keep the default locale of your app.

and offers the same solution I came up with:

> You can override this default locale in links in you active admin pages by passing the locale.

I've edited the wiki page to make this a bit more visible.

**Comment by wpp** [comment]
Hi @timoschilling,

I don't want to annoy you guys, but do you mind re-opening this? I don't believe that passing the locale around is a great solution. (That seems really error-prone and a lot of work).

Or am I misunderstanding the problem?

**Comment by wpp** [comment]
Ok so I've finally figured out what was going on.

I originally followed the [rails guide](http://guides.rubyonrails.org/i18n.html) and set my routes.rb:

    # config/routes.rb
    scope "/:locale" do
      resources :books
    end

which resulted in an error like:

> No route matches {:action=>"index", :controller=>"admin/users"} missing required keys: [:locale]

this was "fixed" by setting

    scope ':locale', defaults: { locale: I18n.locale } do
      ActiveAdmin.routes(self)
    end

as suggested in the current version of the [Switching locale guide](https://github.com/activeadmin/activeadmin/wiki/Switching-locale).
**But** this has the side-effect of all subsequent url_helpers using this locale for url generation. [BTW at least one other person ran into this](https://github.com/rails/rails/issues/13184).

My current work-around can be [found here](https://github.com/wpp/activeadmin/tree/locale_patch):

     lib/active_admin/helpers/routes/url_helpers.rb
     def self.default_url_options         
        (Rails.application.config.action_mailer.default_url_options.merge({locale: ::I18n.locale})) || {}
     end

Now urls are generated as expected.

If someone has an idea how I could fix this without adding locale to the default_url_options everytime, I'd be happy to submit a PR.

**Comment by B3rs** [comment]
I used @wpp monkey patch and works without manually overriding all links...
Now the `default_url_options` method has changed so I adapted it as below

```
lib/active_admin/helpers/routes/url_helpers.rb
def self.default_url_options
    options = Rails.application.routes.default_url_options || {}
    options.merge({locale: ::I18n.locale}) if defined?(::I18n) && ::I18n.locale
end
```
Maybe I can write a PR if somebody still has this issue...

**Comment by wpp** [comment]
Hi @B3rs, glad it helped. I for one would love a PR. I'm not sure why this issue hasn't been re-opened.

**Comment by B3rs** [comment]
@timoschilling what do you think? here the real issue seems to be that we are using the `default_url_options` from the rails initializers instead of the application_controller one (which correctly adds locale).
Is there a way to correctly reference ApplicationController's method or can we just add locale support?

**Comment by sumeetattree** [comment]
Chiming in here because just ran into this issue. [The guides here](https://github.com/activeadmin/activeadmin/wiki/Switching-locale) asks you to provide `locale` option every single time which is cumbersome and error prone.

The urls that were auto generated by active admin like for user emails and such have the locale correctly set on them but all the urls generated by `*_path` methods seem to default to `:en`
