### ISSUE TITLE
Support multiple belongs_to

### ISSUE THREAD

**Issue by knoopx** [activeadmin/activeadmin#221]
_Edit: Original title: Specifing multiple belongs_to does not seem to work_

The following:

```
ActiveAdmin.register Movie do
  belongs_to :provider, :optional => true
  belongs_to :actor, :optional => true
end
```

only generates routes for the `actor`, `provider` is completely ignored

**Comment by emilebosch** [comment]
Well 'ive managed to work around it by just making my own polymorphic controller. And adding the routes myself. Makes total sense. Its a monkey patch but hey. at least it works.

app/controllers/admin/comments_controller.b
```
module Admin
  class CommentsController < ApplicationController
    def create
      commentable.comments.create!(comments_params[:comment])
      redirect_to :back
    end

    def comments_params
      params.permit!
    end

    def commentable
      return House.find_by_slug(params[:house_id]) if params[:house_id]
      return Person.find(params[:person_id]) if params[:person_id]
      raise "Can't find commentable"
    end
  end
end
``` 
routes

```
  ActiveAdmin.routes(self)
  namespace :admin do
    resources :people do
      resources :comments
    end
    resources :houses do
      resources :comments
    end
  end
```

**Comment by jnettome** [comment]
:+1: and thank you @Zequez, good solution :)

**Comment by zerocool4u2** [comment]
Well, working around this i came to this solutions
ActiveAdmin.register Pickup do
	controller do
		belongs_to :client, :warehouse, optional: true
	end
end

and then add the routes, 

namespace :admin do
	resources :clients do
		resources :pickups
	end
	resources :warehouses do
		resources :pickups
	end
end

this gives me support for both nested routes and the resource itself

admin/pickups/....
admin/clients/pickups/...
admin/warehouses/pickups

if you don't want the route for "pickups" i don't know how could you do this, with menu false option at least you can remove it from the navigation bar, but for my case i need it, also the optional: true, allows you to have the belongs without one of the parents, you should work around the forms as well, i'll gonna work with the route to show the corresponding dropdowns depending where i'm to create new pickups in each case

**Comment by gabrieltong** [comment]
+1

**Comment by seanlinsley** [comment]
Github now allows you to add a reaction to comments. If someone wants to add a +1 to this ticket, please do it via a reaction to the first comment on the ticket instead of adding a new comment.

You can also subscribe to the ticket so you receive notifications if anything new happens.

<img width="481" src="https://cloud.githubusercontent.com/assets/688886/14130660/41ebb7fc-f5fa-11e5-8eda-04a411d692c8.png">

**Comment by yoonwaiyan** [comment]
@zerocool4u2 this solution works apparently but it failed to build proper breadcrumbs based on the parent resource. 

For example, I have M-M relationships between Sponsors and Customers so both of has many Sponsorships. While accessing Sponsorships from Sponsor, for example admin/sponsors/5/sponsorships, activeadmin will find resource by Sponsorship instead of Sponsor so it returns wrong `name` for the breadcrumb.

Wondering if there's any workaround on this issue, thanks.

**Comment by zerocool4u2** [comment]
@yoonwaiyan i don't really remember that much about this, but looking at the project i have this on routes 
```ruby
	namespace :admin do
		resources :e_commerces, only: [] do
			resources :pickups
		end
		resources :warehouses, only: [] do
			resources :pickups
			resources :employees
		end
	end
```
maybe the `, only[]`? 
the polymorphic is the other difference that i have, sorry for not been more helpful, but i don't remember that much of this project or activeadmin now :disappointed:

**Comment by blimmer** [comment]
I just ran into a problem with the workaround that prevented all `collection_action`s from working. Instead, they were interpreted as a `GET <model>/:id` instead of `GET <model>/collection_action_name`.

The problem was that the `ActiveAdmin.routes(self)` was after the workaround.

```ruby
# bad
namespace :admin do
  resources :customers do
    resources :sponsorships
  end
  resources :sponsors do
    resources :sponsorships
  end
end
ActiveAdmin.routes(self)

# good
ActiveAdmin.routes(self)
namespace :admin do
  resources :customers do
    resources :sponsorships
  end
  resources :sponsors do
    resources :sponsorships
  end
end
```

Just leaving this comment here in case it helps someone else.

**Comment by johnmcconnell** [comment]
I also would like this

**Comment by Tensho** [comment]
Would like this feature for the polymorphic association

**Comment by itkin** [comment]
+1

**Comment by joshlin** [comment]
+1 for nested and polymorphic

**Comment by steookk** [comment]
+1

**Comment by GBH** [comment]
🎉 Happy 8 year anniversary 🎉 

I was really hoping i was doing something wrong. Sadly I discovered that it's a bug and/or missing functionality.

**Comment by Looooong** [comment]
I have created #6115 for anyone looking forward to this feature enhancement.
