### ISSUE TITLE
boolean filter check_boxes do not work as expected

### ISSUE THREAD

**Issue by marcusg** [activeadmin/activeadmin#2227]
given my model `Page` has a `visible` flag and I have the following filters

```
filter :name
filter :visible
```

accessing the Page AA shows the filters correctly. But I am not able to filter for Pages that are invisible, because leaving the checkbox untouched results in no parameter passed to meta_search. Maybe I'm missing something important here...

**Comment by Shoroh** [comment]
Hi guys!

Is there a better way to make a single checkbox instead of two (with yes & no) if boolean field? I use some trick at the moment:

```ruby
filter :garden, as: :check_boxes, collection: [['Garden', true]], label: ''
```
look at :garden case below:

![screen shot 2015-04-21 at 09 41 46](https://cloud.githubusercontent.com/assets/1865984/7244776/b0bf1b32-e80a-11e4-8dce-ac8ee62468b6.png)
