### ISSUE TITLE
UI for batch actions for all filtered results

### ISSUE THREAD

**Issue by Fivell** [activeadmin/activeadmin#2375]
There are some problems with active_admin trying to update filtered results. For instance I there was about 100 pages where I  should update every record (disable/enable, change attribute, etc) after  I had filtered data with sidebar form ....
To do this I must do the same action 100 times. 
Examples: 
1)I need to update all prices (increase on 10%, decrease on 5%, etc) in some category which has more than 100 000 items. 
2) I need to disable all items which has price >= 100 USD ... (more than 1k records)

Such actions can be done with 1 sql query, but there is no way to do this with current UI.

Are there possible ways to improve this?   Any thoughts? Thanks.

**Comment by Fivell** [comment]
@timoschilling , there is a gem that has all the features for now 
https://github.com/activeadmin-plugins/active_admin_scoped_collection_actions

**Comment by timoschilling** [comment]
@Fivell way not as PR?

**Comment by Fivell** [comment]
@timoschilling, because early alpha, lack of time,  no specs, no localization, not  DRY solution for merging.

**Comment by mmustala** [comment]
I would think integrating DataTables into ActiveAdmin would solve this issue. DataTables is able to filter the data in many ways allowing the user to get exactly the wanted records into the table. Then just use the current batch action methods. And possibly merge my pull request for ability to define a custom batch action dialog. https://github.com/activeadmin/activeadmin/pull/3965

**Comment by jasper-lyons** [comment]
I figured out a fairly light weight solution, by providing a wrapper function around ```batch_action``` in ```ActiveAdmin::DSL``` I could identify a lot of useful information about the ```batch_action``` call that allowed me to apply filters, select all records or just do the default behavior.

Heres the implementation:
```ruby
# ./config/initializers/active_admin.rb
module ActiveAdmin
  class DSL
    def filtered_batch_action(title, options, &block)
      self.batch_action title, options do |ids, options|
        if params[:collection_selection_toggle_all] != "on"
          instance_exec(ids, options, &block)
        else
          # pluck is ActiveAdmin specific, probably needs abstracting
          if params[:q].nil?
            instance_exec(resource_class.pluck(:id), options, &block)
          else
            instance_exec(resource_class.ransack(params[:q]).pluck(:id), options, &block)
          end
        end
      end
    end
  end
end 
```
Which can be used like this:
```ruby
ActiveAdmin.register Post do
  filtered_batch_action :delete do |ids, options|
    # do things as you would in normal batch actions
  end
end
```
This just changes the semantics of the "toggle all" check box when a ```selectable_column``` is provided so that:

* if toggle all is on
    * if a filter is applied
        * filter all the records and return the ids of those that match
    * if filter is not applied
        * return ids of all records
* if toggle all if off
    * return ids of records selected

It definitely suffers from some issues like requiring the active record ```pluck``` function and lacks tests but I hope it can at the very least provide some context for the discussion about how this could be implemented with minimal changes.

**Comment by deivid-rodriguez** [comment]
@Fivell Any suggestions for this issue?

**Comment by Fivell** [comment]
@deivid-rodriguez , this is not an issue  for me now anymore since there are already workaround from  @jasper-lyons  and [gem](https://github.com/activeadmin-plugins/active_admin_scoped_collection_actions)

**Comment by akshar21** [comment]
@jasper-lyons Thanks for the help. its working for me. But there is one change.
instance_exec(resource_class.ransack(params[:q]).pluck(:id), options, &block)
this line won't work. In rails 5 instead of above line we have to use below line for ransack.
instance_exec(resource_class.ransack(params[:q]).**result**.pluck(:id), options, &block)

**Comment by jasper-lyons** [comment]
Thanks @akshar21 . I'm surprised this never made it into a PR. Then you could have submitted it as a code change.

Is this actually still an open issue or is it just unattended but finished?

**Comment by mcfoton** [comment]
Would love to see this implemented built-in, using @jasper-lyons DSL implementation for now.
