### ISSUE TITLE
`has_many` form helper is broken

### ISSUE THREAD

**Issue by sogamoso** [activeadmin/activeadmin#2401]
The `has_many` form helper is generating weird duplicated fields for the fields generated using the `has_many` helper.

![](http://cl.ly/image/1V1n0O1O3t1l/Screen%20Shot%202013-08-08%20at%208.13.47%20AM.png)

As you can see the fields for Property Image are duplicated.

Since I need to customize that view a bit, I have a custom `_form` partial which I created following the instructions in the [documentation](http://www.activeadmin.info/docs/5-forms.html). Here's the code for that view: https://gist.github.com/sebasoga/0e6826fee9986d2cfd5d

I'm using ActiveAdmin `0.6.0` and already tried using latest code in `master` branch with no luck.

**Comment by robbieshepherd** [comment]
this bug just bit me hard. I needed to insert some html into a form, which required me to use a partial. The form wouldn't render properly without including builder: ActiveAdmin::FormBuilder, but because the form also has_many associations, it rendered the association form elements twice each time an association was added. The only way I could solve it was by declaring the standard form in the admin/model.rb, then monkey-patching the FormBuilder < ::Formtastic::FormBuilder has_many_actions method to include the custom html I wanted where I wanted it.
