### ISSUE TITLE
Would persistent stateful index lists be desirable?

### ISSUE THREAD

**Issue by rraub** [activeadmin/activeadmin#2509]
For a few of my Active Admin applications I've found that persisting the parameters for the index pages in the session gives the users a more persistent interface.

Heres what I've been doing to hack this in:
https://gist.github.com/rraub/6735432

Not the most elegant solution, but seems to work well. 

What drove me to do this was seeing users use the index filters to narrow down the resource list, then edit one of the results and return back to the index page of the resource list without any of their filters they had just set.

I'm wondering if this is a feature others might want to, or if there are other use cases for this kind of feature.

**Comment by MissHenesy** [comment]
I ran into this quandary and I have applied my own special band-aid.

I've used a combination of the active_admin.js.coffee file for some javascript magic, combined with a little session magic on the server side in my Rails file.

My objective:: Persist the user's filters from the index page to the edit page, so that when a record is edited, they can return to their filtered list.

In active_admin.js.coffee::
I manipulate the href values of the "Edit" link on the index page, and the "Cancel" button on the edit page, so that each button retains the query string, like so::

CODE FROM ACTIVE_ADMIN.JS.COFFEE FILE::
=========================================================
# app/assets/javascripts/active_admin.js.coffee
#= require active_admin/base 
$ ->
  querystring = window.location.search
  
  linkbutton_edit = $("#active_admin_content").find("a.edit_link")
  linkbutton_cancel = $("#active_admin_content").find("li.cancel").children("a")

  if linkbutton_edit.length && querystring
   # Append the querystring to the end of each Edit link on the index page
    linkbutton_edit.each ->
      href = $(this).attr("href") + querystring
      $(this).attr "href", href
      return

  if linkbutton_cancel.length
    # Change the text from "Cancel" to "Return to List"
    linkbutton_cancel.text("Return to List")
    if querystring
      # Append the querystring to the href value
      linkbutton_cancel.attr("href", linkbutton_cancel.attr("href") + querystring)
    else
     # if no querystring, then use the url address from the document.referrer (heh heh heh)
      if document.referrer.split('?')[1]
        linkbutton_cancel.attr("href", linkbutton_cancel.attr("href") + document.referrer.split('?')[1])

CODE FROM APP/ADMIN/MY_ADMIN.RB FILE
=========================================================

# Placement of Submit/Cancel Buttons in the .rb file ... this is within the "form do" routine::
form do |f|
    # form stuff
     f.semantic_errors *f.object.errors.keys
     inputs "Stuff to Update" do
         input :some_field
     end
    panel "Submit Buttons" do
       para "Press cancel to return to the list without saving."
       actions
    end
end

#Controller to manipulate Submit button
  controller do
    def update
      super do |success,failure|
        success.html { redirect_to get_redirect_url }
      end
    end
    def get_redirect_url
      if ["edit?"].include? request.env["HTTP_REFERER"]
        session[:redirect_url] = request.env["HTTP_REFERER"]
      else
        session[:redirect_url]
      end
    end
  end
=================================================

Nuthin' to it. Probably not the most elegant solution, but it works for me :-)

**Comment by abrambailey** [comment]
I strongly support making this the default behavior, or at least making it settable in an initializer.
