### ISSUE TITLE
CSS missing in production

### ISSUE THREAD

**Issue by evandcoleman** [activeadmin/activeadmin#2800]
It looks like the admin panel has no CSS in production. Everything works as expect in development, however. Here's a screenshot:

![screen shot 2013-12-19 at 12 58 33 am](https://f.cloud.github.com/assets/706048/1780403/a4bed4c6-6872-11e3-984d-d0384e881f47.png)

**Comment by anshratn1997** [comment]
In rails newer version, assets are served by the Sprockets middleware from` app/assets` directory instead of `public/assets` directory. 
For the production environment rails precompiles these files to public/assets by default and files are served from `public/assets` directory.
For any non-production environment like staging or preprod you have to set this config `config.assets.compile = true`
in the `config/environments/staging.rb` or `config/environments/preprod.rb`  file.
This has worked for me.
For reference, 
https://guides.rubyonrails.org/asset_pipeline.html
