### ISSUE TITLE
Dynamic scopes and filters

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#2818]
It's a common misconception (#2340, #2781) that scopes will behave dynamically, but in reality they're loaded once, when the server boots.

I'm open to DSL suggestions.

**Comment by itkin** [comment]
+1

**Comment by heaven** [comment]
Any luck with this?

**Comment by gingerlime** [comment]
also wondering about this... in our particular case, we have a "heavy" scope, which I only want to run when it's explicitly needed. Otherwise, the index page would run a `count` on the scope to show how many entries there are, but I'd rather avoid it and only apply it with an action item or something... Would be great to be able to apply the scope only with the scope param, but this doesn't seem to work if the scope isn't specified.
