### ISSUE TITLE
Not yet checked out. Run bundle install...

### ISSUE THREAD

**Issue by ipranay** [activeadmin/activeadmin#2899]
I am using the the following line in the gem file:
`gem 'activeadmin', github: 'gregbell/active_admin'`

and even after running 'bundle install' multiple times today... I keep getting the following error:

`git://github.com/gregbell/active_admin.git (at master) is not yet checked out. Run 'bundle install' first.`

**Comment by dredozubov** [comment]
I still encounter this issue with bundler 1.8.0:
`git://github.com/activeadmin/activeadmin.git (at master) is not yet checked out. Run `bundle install` first.`

**Comment by timoschilling** [comment]
This problem happen when bundler has a problem with the checkout / clone of a repository based gem.

There are many thinks that can help, for me the best solution is to delete the bundle cache folder.

While this problem is not related to ActiveAdmin and many people posting "same here", I'm going to lock this Issue now!
