### ISSUE TITLE
Active admin handles composite_primary_key based models "Exception"ally badly :P

### ISSUE THREAD

**Issue by ktaragorn** [activeadmin/activeadmin#3220]
This is not exactly a bug report because this is not a regular rails practise.. but Is it possible to handle models which use composite_primary_key gem to use multiple columns as a primary key? In my case I use it on a (more than just a ) join table of 2 other models. I could add a seperate id column, but it seems to be a composite key is the more natural way, so I was wondering
1. Is there any fundamental limitation to active admin which makes handling this impossible
2. If not, can I hack something together which will make it work?
3. Is this something I can gemify eventually?

Current problems.

a) Visiting one of the 2 models which `has_many` the join model, will cause this errror

```
undefined method `broadcasts_id_eq' for Ransack::Search<class: Match, base: Grouping <combinator: and>>:Ransack::Search
```

Here broadcasts is the joint table name. From the logs this appears to be code that generates the filters in the right

Visiting the join model itself works ok, except it shows the primary key as 1 column, and clicking on it  leads to an error `["bar_id", "match_id"] is not a symbol` where that array is the key.

Tried googling for this issue, but all I found was [this unanswered google groups post](https://groups.google.com/forum/#!topic/activeadmin/WktZUAJYYas) and [this SO post, with one rather negative post with a dead link](http://stackoverflow.com/questions/13825291/active-admin-composite-primary-keys)

**Comment by TylerRick** [comment]
I needed to get ActiveAdmin working with some models that use the composite_primary_keys gem.  This is how I ended up working around the various issues that came up:

```ruby
ActiveAdmin.register Thing do
  controller do
    defaults :finder => :find_by_csv_ids

    # Based on a suggestion from https://github.com/activeadmin/activeadmin/issues/279
    alias_method :aa_resource_path, :resource_path
    def resource_path(*args)
      options = args.extract_options!
      record = args.first
      aa_resource_path record.csv_ids, options
    end

    alias_method :aa_edit_resource_path, :edit_resource_path
    def edit_resource_path(*args)
      options = args.extract_options!
      record = args.first
      aa_edit_resource_path record.csv_ids, options
    end

    alias_method :aa_resource_url, :resource_url
    def resource_url(*args)
      options = args.extract_options!
      record = args.first
      aa_resource_url record.csv_ids, options
    end
  end

  form do |f|
    f.semantic_errors

    # This doesn't work with CPK:
    #   f.inputs          # builds an input field for every attribute
    # lib/formtastic/helpers/reflection.rb:30:in `association_primary_key_for_method' fails with:
    #   undefined method `to_sym' for [:subject_id, :school_year_name]:Array
    #
    # So we have to explicitly list all inputs to include in the form:
    inputs 'Details' do
      input :name
      #…
    end

    f.actions
  end

  # Remove filters to work around errors like:
  #   undefined method `things_id_eq' for Ransack::Search
  config.filters.each {|name, value| remove_filter(name) }
end
```

`csv_ids` returns a comma-separated value for the composite primary key (for example "111,222").  (You could also override `to_param` to return `csv_ids` but I couldn't in my app.). `find_by_csv_ids` parses this CSV and passes the resulting composite ID on to `find`.

I defined those in `lib/active_record/composite_primary_key_extensions.rb` like so:
```ruby
ActiveRecord::Base::CompositeClassMethods.class_eval do
  def find_by_csv_ids(csv_ids)
    find CompositePrimaryKeys::CompositeKeys.parse csv_ids
  end
end
ActiveRecord::Base::CompositeInstanceMethods.class_eval do
  def csv_ids
    Array(id).join(',')
  end
end
```

Tested with:
* Rails 3.2
* composite_primary_keys 5.0.14
* activeadmin 1.0.0.pre (15687751fa9ff637a7b39aae36d6b35abdb8fed4)

Hope someone else finds this useful!

**Comment by TylerRick** [comment]
Good news. Just realized that a few of the workarounds I suggested aren't even necessary after all:

1. `defaults :finder => :find_by_csv_ids` doesn't appear to be necessary.  `composite_primary_key` already makes it so that `Thing.find(Thing.last.id.to_s)` works (in addition to `Thing.find(Thing.last.id)`), (where `Thing#id` is an array of IDs).  So as long as long as the id param is coming through as a comma-separated list of IDs like "111,222" this part should "just work" without any help.
2. Instead of using a custom `csv_ids` method, you can just do `record.id.to_s`.  This works because `composite_primary_key` changes the `id` method so that it returns a `CompositePrimaryKeys::CompositeKeys` object (which is a subclass of Array) whose `to_s` does the `joins(',')` automatically.
3. `to_param` by default will just return `id`.  So thanks to the `to_s` conversion they provided, it should already give us nice IDs like "111,222".  The only reason I needed to override `resource_path`, etc. is because I had a custom `to_param` that returned one of the IDs in the composite primary key.  Those workarounds are only needed if you happened to use a custom `to_param`, as discussed in #279.
4. You don't have to remove *all* filters — you should only have to remove any filters for foreign keys that use composite keys.

Here's my simplified code:

```ruby
ActiveAdmin.register Thing do
  form do |f|
    f.semantic_errors

    # This doesn't work with CPK:
    #   f.inputs          # builds an input field for every attribute
    # lib/formtastic/helpers/reflection.rb:30:in `association_primary_key_for_method' fails with:
    #   undefined method `to_sym' for [:subject_id, :school_year_name]:Array
    #
    # So we have to explicitly list all inputs to include in the form:
    inputs 'Details' do
      input :name
      #…
    end

    f.actions
  end

  # The 'other_composite_key_thing' filter causes:
  #   undefined method `to_sym' for [:some_id, :other_id]:Array
  config.filters.each {|name, value| remove_filter(name) if name.to_s.in? %w[other_composite_key_thing]}
end
```
