### ISSUE TITLE
Login and logout redirection wrong when using config.relative_url_root

### ISSUE THREAD

**Issue by etonline** [activeadmin/activeadmin#3307]
Hi,

I am experiencing problem for login and logout redirection when entering Active Admin after set `config.relative_url_root`.

I have nearly no experience about deploying rails app under sub-directory.
However, I finally figured out that I can use `scope` in routes.rb plus `config.relative_url_root` setting to let rails produce correct asset paths.
Here are my settings:
For **routes.rb**

``` Ruby
Rails.application.routes.draw do
  scope '/myapp' do
  resources :people
  root 'people#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end
```

In **config/environments/production.rb**
`config.relative_url_root = "/myapp"`

Everything works fine, except when I enter `http://myhost/myapp/admin`, it redirects me to 
`http://myhost/myapp/myapp/admin/login`, but I can manually enter `http://myhost/myapp/admin/login` for login.
Also when logout, it goes to `http://myhost/bigdata/bigdata/admin`

I found #101 seems to be related to this issue, but also not being resolved yet.
Is it a bug, or I am not using the correct way for placing my app under sub-directory?

Thanks for your help in advance!

**Comment by noahlh** [comment]
Hi guys - I'm running into this exact issue on Rails 4 & ActiveAdmin on master (as of today).

I'm not 100% sure that what Timo wrote is accurate - but I'm entirely happy to be corrected.  As of Rails 4.2, the [guide still says](http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root) that setting `config.relative_url_root` or the environment variable `ENV['RAILS_RELATIVE_URL_ROOT']` is the way to deploy Rails to a subdirectory.

I'm going to dig into the AA code in a bit, but from a cursory look, Devise is setting up the directory structure properly, i.e. `/my_subdir/admin/login`, but AA is doing a redirect to `/my_subdir/my_subdir/admin/login`.  Someone more familiar with the code might be better suited than I to point out exactly where that is.

Has anyone else encountered this issue and/or figured out a resolution?  I'll report back what I find.

**Comment by noahlh** [comment]
One change to the configuration above (there's a missing `end` so not sure if intentional or not) -- I've found that to fully put everything under /my_subdir, it's necessary to both use `config.relative_url_root` as well as put all of your routes under a scope :my_subdir.

So the config file above in my case is:

````ruby
Rails.application.routes.draw do
  scope '/my_subdir' do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    resources :people
    root 'people#index'
  end
end
````

Everything works fine if you're logged in -- the only problems are that if you're not logged in, AA is redirecting you to `/my_subdir/my_subdir/admin/login` and if you just log out, you're being sent to `/my_subdir/my_subdir/admin`.  

I'm pretty sure this can be hacked into working through manual entries in `routes.rb`, but obviously that's not a long-term fix or optimal.

Any thoughts appreciated!

**Comment by betesh** [comment]
Here is my solution:

Assuming your devise model is called user, you've presumably configured this in your AA initializer:

    config.authentication_method = :authenticate_user!

The problem is that, with Devise's implementation of this method, and AA's routes, this redirects you to `/login` when you are not logged in.  All you need to do is override this method in ApplicationController.

    # app/controllers/application_controller.rb
    def authenticate_user!
      if user_signed_in?
        super
      else
        redirect_to new_user_session_path 
      end
    end
