### ISSUE TITLE
Render comments outside of resource show

### ISSUE THREAD

**Issue by kochis** [activeadmin/activeadmin#3327]
I can't seem to find a way to render the ActiveAdmin comments outside of the `show` action. Is this even possible?

I've tried calling the `active_admin_comments` method directly on `ActiveAdmin::Comments::ShowPageHelper`, but can't seem to get it to work.

What I'm trying to do is render the comments in the view from a `member_action` method. Is there perhaps a better way to do this?

**Comment by BRZInc** [comment]
Thank you very much for this hint!

I've tried to use this advice and finally comments are shown just once on the page, but at the same time comments addition form is missing.

Could you advice me, how to fix this?

**Comment by andywenk** [comment]
@BRZInc I assume you try to add the comments form to the edit view. That will not work since you cant put a form into a form. The edit view looks like this with (not working) the comments form:

    form do |f| 
      # form fields
      active_admin_comments_for(resource)
    end

You will see the comments and the form but not the comments form will be submitted but the whole resource form. 

If you just want to see the comments, you can recreate the comments by yourself without creating a form:

    form do |f|
      # form fields

      panel "Comments", class: 'comments player panel' do
        ActiveAdmin::Comment.where(resource_id: params[:id]).map do |comment|
          admin = AdminUser.find(comment.author_id)
          div class: 'active_admin_comment' do
            div class: 'active_admin_comment_meta' do
              h4 class: 'active_admin_comment_author' do
                a admin.email, href: admin_admin_user_path(comment.author_id)
              end
              span l admin.created_at
            end
            div class: 'active_admin_comment_body' do
              text_node "<p>#{comment.body}</p>".html_safe
            end
          end
        end.join.html_safe

        text_node "#{button_to 'Neuer Kommentar', edit_admin_player_path(player.id)}".html_safe
      end
    end

You also take the result from `active_admin_comments_for(resource)` and throw away the form in the string.

**Comment by timoschilling** [comment]
@andywenk I think don't need the `join.html_safe` and you can use `each`

**Comment by andywenk** [comment]
@timoschilling yup you are right - that was still the code when I debugged the values without creating any HTML. Updated my comment. Thanks!
