### ISSUE TITLE
Bug in 'seems_searchable?' / ransack-related

### ISSUE THREAD

**Issue by mrbrdo** [activeadmin/activeadmin#3409]
When I create a custom ransacker in my model:
```
  ransacker :last_signup_step do
    Arel.sql("company_meta->>'lastSignupStep'")
  end
```

And then a filter in ActiveAdmin:
```
filter :last_signup_step, as: :numeric
```

It works, but it always does the equals comparison, even if I select something else from the dropdown. It seems because the `select_and_search` css class is not added to the field.
This comes from this line from ActiveAdmin source: `(opts[:class] ||= '') << ' select_and_search' unless seems_searchable?`

The method `seems_searchable?` returns true if there is a ransacker defined with that name, I think that is causing the issue. Maybe it was bugged after ransack was introduced? I think the metasearch methods were named like `field_equals` but in ransacker it's just `field`.

**Comment by seanlinsley** [comment]
`seems_searchable?` checks `ransacker?` specifically so you can use a ransacker with `as: :select`
```ruby
      class SelectInput < ::Formtastic::Inputs::SelectInput
        include Base

        def input_name
          return method if seems_searchable?

          searchable_method_name.concat multiple? ? '_in' : '_eq'
        end
```

The fact that Ransack doesn't support the different predicates seems like a Ransack bug, not an Active Admin bug.

**Comment by seanlinsley** [comment]
Or maybe Ransack does support it and we're just not allowing it? I'm not sure. But it seems like #3510 more succinctly explains the desired feature, so I'm going to merge this ticket into it.

**Comment by llawlor** [comment]
My temporary jQuery solution until this is fixed:

// when the document is ready
$(document).ready(function() {
  // add class 'select_and_search' to all elements with class 'filter_numeric'
  $('.filter_numeric').addClass('select_and_search');
});

**Comment by whatcould** [comment]
Just a note to clear up the confusion above: I think this is an ActiveAdmin bug, not a Ransack bug. Ransackers **do** support the predicates, but when filters are created for a ransacker (eg `filter :name_reversed`), AA wouldn't create the correct type of filter, since it would assume the query name should be `name_reversed` instead of the predicated name, eg`name_reversed_cont`.

My fix works great for the simple ransacker use cases I found, including the one I added to the sample Rails app in ActiveAdmin; I guess it's possible that some ransackers (ones that take parameters?) do not use predicates?
