### ISSUE TITLE
Index filtering for renamed resources

### ISSUE THREAD

**Issue by kochis** [activeadmin/activeadmin#3477]
I have a renamed resource in my admin

``` ruby
ActiveAdmin.register User, as "Pending User" do
   filter :email
end
```

I am also using the following for populating the index page

``` ruby
controller do
  def index
    @pending_users = User.pending.page(params[:page]).per(10)
  end
end
```

However, I'm getting the following error after adding filters to the page

```
An ActionView::Template::Error occurred in pending_users#index:

  First argument in form cannot contain nil or be empty
```

Any help would be greatly appreciated.

**Comment by gerryhd** [comment]
So is there absolutely no way to implement extra functionality to the index method? Initially I thought that because you can override create and edit you would be able to override index as well. In my case I need to perform a search on all attributes by a given parameter and only show the results, which I achieved with this line 
        `@applicants = Applicant.joins(:user).where('username LIKE :search OR email LIKE :search OR name LIKE :search OR last_name LIKE :search', search: "%#{query}%").page(params[:page]).per(10)`

But I'm getting same error as OP after running super
Any help or suggestion to implement it some other way is also appreciated
