### ISSUE TITLE
default filter should list custom ransackers

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#3510]
If there is a custom runsacker defined, like this:

``` ruby
class User < ActiveRecord::Base
  ransacker :fullname do
    Arel.sql("CONCAT(`firstname`, ' ', `lastname`)")
  end
end
```

There should be a automatic generated filter for `fullname`, like the filters for each other field.

**Comment by xhero** [comment]
Is there any chance to have the problem fixed? I had to do a very ugly javascript workaround to get the searched filter value in the textbox

**Comment by whatcould** [comment]
Added a pull request. As @timoschilling points out above, the comment on #3409 does suggest a workaround; but that workaround is a little brute force, and you may get confusing filter issues since any filter that's not a ransacker will `seems_searchable?`. If you want to fix this issue now, use this in an initializer:

``` ruby
module ActiveAdmin
  module Filters
    module FormtasticAddons
      def seems_searchable?
        has_predicate? || scope?
      end
    end
  end
end
```
