### ISSUE TITLE
Enhance has_many :allow_destroy to take a string

### ISSUE THREAD

**Issue by lordjavac** [activeadmin/activeadmin#3799]
Currently the :allow_destroy parameter for has_many in a form accepts a boolean to indicate whether it should be present or not. It would be nice to pass a string to be able to change the label on the generated checkbox.

I think this would help the readability of the destroy action when used on a join model.

What I'd like would look something like:

``` ruby
semantic_form_for @category do |f|
  ...
  f.has_many :things, allow_destroy: 'Remove from this category' do |thing|
    ...
  end
end
```

Which would use the given string for the destroy label instead of the default "Destroy" that is currently in place.

**Comment by varyonic** [comment]
For better or worse the `allow_destroy` setting has already been overloaded so that a passed String is interpreted as a method to call to determine if `allow_destroy` is true.  The label displayed is I18n.t('active_admin.has_many_delete') so I guess you could extend this to check for a resource specific translation first.
