### ISSUE TITLE
ActiveAdmin styles are applied on non-ActiveAdmin pages

### ISSUE THREAD

**Issue by unhinged** [activeadmin/activeadmin#3819]
I just added ActiveAdmin to an existing site and was pretty disappointed to see buttons and links across my site to be completely changed, having inherited the ActiveAdmin styles. Huge bug! ActiveAdmin styles should only be applied to ActiveAdmin pages. The styles on the hidden SCSS files you created should be prefixed with the `body.active_admin` class or some other equivalent. I shouldn't have to rewrite my unrelated CSS to accommodate this gem.

For instance, the `active_admin.css` file contains the following: 

    /* line 11, /Users/Jeff/.rvm/gems/ruby-2.1.4/bundler/gems/activeadmin-a0bf8da21b7a/app/assets/stylesheets/active_admin/components/_buttons.scss */
    a.button, a:link.button, a:visited.button, input[type=submit], input[type=button], button {
      -webkit-border-radius: 200px;
      -moz-border-radius: 200px;
      border-radius: 200px;
      display: inline-block;
      font-weight: bold;
      font-size: 1.0em;
      font-family: Helvetica, Arial, sans-serif;
      line-height: 12px;
      margin-right: 3px;
      padding: 7px 16px 6px;
      text-decoration: none;
      -webkit-font-smoothing: antialiased;
      background: #838a90;
      background: -webkit-linear-gradient(-90deg, #838a90, #414549);
      background: -moz-linear-gradient(-90deg, #838a90, #414549);
      background: linear, 180deg, #838a90, #414549;
      filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#FF838A90', endColorstr='#FF414549');
      -ms-filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#FF838A90', endColorstr='#FF414549');
      text-shadow: black 0 1px 0;
      box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1), 0 1px 0 0px rgba(255, 255, 255, 0.2) inset;
      border: solid 1px #484e53;
      border-color: #484e53;
      border-top-color: #616a71;
      border-right-color: #484e53;
      border-bottom-color: #363b3f;
      border-left-color: #484e53;
      color: #efefef;
    }

In order to not effect the normal application pages (not ActiveAdmin), the selector should be:

    .active_admin a.button, .active_admin a:link.button, .active_admin a:visited.button, .active_admin input[type=submit], .active_admin input[type=button], .active_admin button { }

I have a basic install per the [docs](http://activeadmin.info/docs/documentation.html) with few registered models. No additional config.

**Comment by timoschilling** [comment]
Please read https://github.com/activeadmin/activeadmin/blob/master/docs/14-gotchas.md#css

**Comment by unhinged** [comment]
Thanks @timoschilling. I did read that. However, I think this issue is still unacceptable in its current implementation. Forgive me for being blunt, but it's just lazy. The behavior is entirely unexpected and quite drastic. 

The change I suggested would be quick, but I suspect that it's not going to happen. If the plan is not to change it, then I would request that the documentation be updated to put more visibility into this issue. Currently, the docs treat it as if the mentality is, "Oh, by the way, you might want to do this..." In reality, I would expect this to be a required step in nearly every installation. As such, it deserves more attention.

**Comment by unhinged** [comment]
Actually, this issue isn't addressed at all activeadmin.info/docs.

**Comment by ccallebs** [comment]
@unhinged activeadmin.info is deprecated in favor of the other docs. No one on the contributing team has access to that domain, if I recall.

**Comment by ccallebs** [comment]
@unhinged @timoschilling That being said, it wouldn't be a bad idea to scope everything to a body class to remove any chance of this occurring in the future.

**Comment by timoschilling** [comment]
@ccallebs I have now access to [activeadmin.info](http://activeadmin.info), it now points to the [activeadmin.info](https://github.com/activeadmin/activeadmin.info) Github repo, but the content is still out of date. We or I should add a banner on the page until it's updated.

@unhinged the problem is, if you use the `require_tree` in your application.css the complete activeadmin css is include in your frontend css. I think that's nothing that you want! Yes you are right wrapping all in a `.activeadmin` class will solve the overwriting, but is still dirty way you have all the activeadmin css in the frontend. We provide two different solutions, that's enough. For me I will don't change that and don't accept PR for that.

**Comment by unhinged** [comment]
@timoschilling You're right. Having the AA CSS load on front end isn't ideal either. And the existing solution to move the SCSS files to `vendor/` is simple enough. The problem, as it appears to me, is mostly a documentation issue now.

1. The CSS cascades into non-AA pages by default when following the either the new or old documentation.
2. The old documentation is still accessible, shows up first on search results, and does not mention this issue.
3. The new documentation does mention it, but it is buried 14 pages later. Perhaps a link can be added to the end of 0-installation.md in order to make the Gotchas more visible to noobs like myself.

Is there a reason why the generator doesn't automatically put the SCSS files in the `vendor/` folder? I've never built a generator before so I don't know if that is possible or if that would cause other issues. That seems like a good way to get annoying people like me off your back ;)

Really though, this is a great gem and I appreciate your efforts. I'm just trying to help.

**Comment by timoschilling** [comment]
1. The problem is not activeadmin at this point, it's the default application.css file with his `require_tree .`, which includes all css in the application file.
2. The old documentation is a problem, sure. Some one needs to find the time to update it, or to add a outdated marker. The Github Readme has two notes about it.
3. We can't put everything on the first page
4. The Rails guides says: "vendor/assets is for assets that are owned by outside entities, such as code for JavaScript plugins and CSS frameworks.", this is not the case for activeadmin. `activeadmin.css` is a file for customizing activeadmin and not activeadmin lib code.

**Comment by unhinged** [comment]
1. You can't dismiss `require_tree .` as an illegitimate technique. It is endorsed by Rails and a significant portion of the Rails community. Of the dozens (hundreds?) of gems I've used, I've never had a problem like this where a gem produces conflicting CSS with my application. It is only activeadmin that I have had a CSS problem with.
2. Cool. I'll be happy to add a comment to the top of activeadmin.info and a link to the GitHub repo if you would accept the PR.
3. I wasn't suggesting putting everything on the first page. Only a comment that the default setup may be cause problems for some users and that they may be interested in checking out the "Gotchas."
4. This makes sense. However, `vendor` folder is for outside code, and if the CSS is not outside code, then why are you advocating moving the files to the `vendor` folder as an acceptable solution? You are actively suggesting that I break Rails' best practices and guidelines.

**Comment by timoschilling** [comment]
1. How many gems do you use that have a own css, which can be customized?
2. You can do that.
4. It don't make sense, `vendor` is for 'external' code, for example a thirty party lib. But `activeadmin.css` is a part of your application to customize the lib code. Where are your ActiveAdmin Model definitions? In your App folder like every other code! The problem is that the default Rails behavior (`require_tree .`), don't support more that one css file that can be called from the outside.

**Comment by ccallebs** [comment]
@timoschilling @unhinged After some searching, there's another option. As part of the AA install process, we could use the `stub` option in the manifest.

```
*= stub admin
```
Not saying this is what we want to do, but it's an option.

**Comment by ccallebs** [comment]
@timoschilling @unhinged This is the source I found it:

http://stackoverflow.com/questions/9255787/asset-pipeline-excluding-an-admin-css-file

**Comment by arif362** [comment]
same problem i faced and i have solved this following bellow :
 1) Firstly you have to create a directory named assets in the vendor directory,

 2) Then in the assets directory of vendor folder you have to create two directories (i) stylesheets and second one is (ii) javascripts. 

3) After that  you have to move the active_admin.scss file from assets/stylesheets to vendor/assets/stylesheets and  the active_admin.js.coffee file from assets/javascripts to vendor/assets/javascripts,

 And finally restart your rails server then reload your apps.  Hope this will work for you .

**Comment by ashishprajapati** [comment]
Thanks @arif362 :) It helped me :)

**Comment by Tresor11** [comment]
@arif362 +1
