### ISSUE TITLE
css box-sizing deprecation warning

### ISSUE THREAD

**Issue by andywenk** [activeadmin/activeadmin#3832]
Hi,

we are using ActiveAdmin 1.0.0pre. There is the following deprecation warning flooding our logs:

    WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
    on line 410 of /var/www/production/shared/bundle/ruby/2.2.0/gems/bourbon-4.2.1/app/assets/stylesheets/_bourbon-deprecated-upcoming.scss, 
    in `box-sizing' from line 4 of /var/www/production/releases/20150305084947/vendor/cache/activeadmin-e27ccba8a7ea/app/assets/stylesheets/active_admin/structure/_title_bar.scss ...

As the message tells and as it can be seen at http://caniuse.com/#search=box-sizing, there is no need for prefixing any more. My suggestion is to remove the mixin in https://github.com/activeadmin/activeadmin/blob/6bde1f57ec5f9b724c21e5af146678f4ade839bc/app/assets/stylesheets/active_admin/mixins/_utilities.scss#L11 and change all places where it is used. A quick search in the compiled CSS file showed 15 of them.

If you agree, I am happy to send a PR.

Cheers

Andy

**Comment by timoschilling** [comment]
You miss understand that warning. The warning mean this mixin: https://github.com/thoughtbot/bourbon/blob/86d2147511265db9cdb35b497e195b8c4649ee98/app/assets/stylesheets/_bourbon-deprecated-upcoming.scss#L407
But ActiveAdmin has his own one.
It look's like the bourbon one has the higher load order.

What we can do is to remove the mixin usage, since #3824 is merged, the mixin is only a oneliner so we don't need them anymore.

**Comment by andywenk** [comment]
ok @timoschilling - so you suggest to remove this line?

https://github.com/thoughtbot/bourbon/blob/86d2147511265db9cdb35b497e195b8c4649ee98/app/assets/stylesheets/_bourbon-deprecated-upcoming.scss#L408

**Comment by timoschilling** [comment]
No to remove the line that you say and no longer to use the mixin.

**Comment by andywenk** [comment]
ah got it - thanks a bunch ;-)
