### ISSUE TITLE
redirect to last viewed scope after "destroy" batch action

### ISSUE THREAD

**Issue by vizvamitra** [activeadmin/activeadmin#3833]
I have noticed some confusing behaviour.

For example I want to delete lots of non-moderated records. First of all, I navigate to not_moderated scope. When I select all records via the checkbox in table header and trigger "destroy" batch action, records are being deleted and I'm being redirected to another, default scope.

This is confusing. If I'll not notice that the scope has changed and keep selecting all records and deleting them, it won't be good.

Or may be there already is a way to make ActiveAdmin redirect to the last viewed scope after the destroy batch action?

**Comment by timoschilling** [comment]
We have the same behavior for search, sort and pagination.

**Comment by maca** [comment]
+1

I find the behaviour of returning to unscoped collection listing not only confusing but dangerous, since can be delicate to batch destroy and being under the impression that the collection is still scoped can lead to performing unwanted destruction.

Solution is pretty simple by replacing `redirect_to active_admin_config.route_collection_path(params),` with `redirect_to :back,` in

https://github.com/activeadmin/activeadmin/blob/b44b4f4896ef78b50c35c82a343356d68b937cde/lib/active_admin/batch_actions/resource_extension.rb#L77

**Comment by varyonic** [comment]
This possibly just needs a test in features/index/batch_actions.feature to verify the fix so we can merge it.

**Comment by abrambailey** [comment]
By the way, this isn't just occurring in batch actions. If I delete a line item while in a filtered view, I'm returned to the unfiltered view afterwards. Also, if I go to edit an item and save, I am returned to the unfiltered view. My personal preference would be a "save index state" option in the active admin initializer that brings behavior similar to https://datatables.net/examples/basic_init/state_save.html

**Comment by truongnmt** [comment]
This should work
```
batch_action :destroy do |ids|
    batch_action_collection.find(ids).each do |interview|
      interview.destroy
    end
    redirect_to request.referer, notice: "Successfully destroyed interviews."
  end
```

**Comment by varyonic** [comment]
@deivid-rodriguez you self-assigned. Your thoughts?

**Comment by deivid-rodriguez** [comment]
I forgot I had self-assigned this! I probably did this because I run into it myself and wanted to fix it. My thoughts are that this should be the default behavior.

**Comment by abrambailey** [comment]
`redirect_to request.referer` works, thanks.
