### ISSUE TITLE
Proposal to remove the default user

### ISSUE THREAD

**Issue by sindrenm** [activeadmin/activeadmin#3988]
We've been using ActiveAdmin a lot, and it's really great, but there is this one thing that really bugs us everytime we run the initializer, and that is the default admin user migration that is being generated. We believe that this is completely unnecessary and a huge security risk in the (perhaps rare) case that the developers forget to either remove the user or change its credentials after deploying the app to a production environment. We find it much safer (and more natural) that the first admin user must be explicitly created through something like a console session.

Tracked down the line of code that adds the user creation to the Devise migration here, just so there's no confusion as to what I'm talking about here:

https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/lib/generators/active_admin/devise/devise_generator.rb#L60

Thanks. :smiley:

**Comment by jgorset** [comment]
:+1: on removing the default administrator; secure by default.

**Comment by mrtorks** [comment]
:+1:

**Comment by seanlinsley** [comment]
It definitely should not be in a migration. Instead, perhaps it should be added to the seed data. Additionally, the initializer could print out a message telling the developer to run this line of code.

I haven't run the initializer on my own projects in years, or I had already set up Devise, so this hasn't been a pain point for me.

**Comment by timoschilling** [comment]
:+1: for @seanlinsley

**Comment by scarver2** [comment]
:thumbs down: on removing the default user

The default AdminUser is part of the simplicity of setting up ActiveAdmin and matches the flow of Rails' generators.. It _is_ a security risk because of the hard-coded password. +1 for Sean's idea of an interactive installer. It should prompt if 

For anyone not wanting to skip creating the default user, it's quite simple:
`rails g active_admin:install --skip-users`

However, I do question the AdminUser being in a migration file. It seems better suited for a seeds file.

Either way, an experienced ActiveAdmin developer should already be aware of the default user and make changes to the email address and password. Having used ActiveAdmin for countless projects, the default user has not posed an issue for me. It certainly makes it easy to teach ActiveAdmin to noobs.

**Comment by scarver2** [comment]
:tada: Works like a champ and removes the security issue that was present in the migration file. If a developer uses seeds in production, I recommend using the [Seedbank](https://github.com/james2m/seedbank) gem or [Sprig](https://github.com/vigetlabs/sprig) gem to partition seeds into environments to avoid adding the default AdminUser credentials.
