### ISSUE TITLE
RoR app not working after active_admin install.

### ISSUE THREAD

**Issue by souljatechie** [activeadmin/activeadmin#3989]
I am new to Ruby and RoR, and I am having an issue with my web app not loading after I install active_admin. I am not entirely sure what all i am doing wrong here, but all my sites, including my rails app, work fine until i install Active_admin (rails apps are the only ones affected by active admin). This seems to be with either Passenger or active_admin. I have also created the same ticket for Passenger.

Here are the things i know:

Rails 4.2.1
gem -v 2.4.8
passenger -v Phusion Passenger version 5.0.9
ruby -v ruby 2.0.0p598 (2014-11-13) [x86_64-linux]

Gemfile:
```
source 'https://rubygems.org'

Bundle edge Rails instead: gem 'rails', github: 'rails/rails'

gem 'rails', '4.2.1'

Use sqlite3 as the database for Active Record

#gem 'sqlite3'
gem 'mysql'

#added for attr_accessible
gem 'protected_attributes'

gem 'activeadmin', github: 'activeadmin'
gem 'sass-rails', github: 'rails/sass-rails'
gem 'ransack', github: 'activerecord-hackery/ransack'

gem 'devise'
gem 'arbre'
gem 'bourbon'
gem 'formtastic'
gem 'inherited_resources'
gem 'kaminari'

#gem 'ruby-mysql'
#gem 'libv8', '3.16.14.3'

Use SCSS for stylesheets

#gem 'sass-rails', '~> 5.0'

Use Uglifier as compressor for JavaScript assets

gem 'uglifier', '>= 1.3.0'

Use CoffeeScript for .coffee assets and views

gem 'coffee-rails', '~> 4.1.0'

See https://github.com/rails/execjs#readme for more supported runtimes

#gem 'therubyracer', platforms: :ruby

Use jquery as the JavaScript library

gem 'jquery-rails'

Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks

gem 'turbolinks'

Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder

gem 'jbuilder', '~> 2.0'

bundle exec rake doc:rails generates the API under doc/api.

gem 'sdoc', '~> 0.4.0', group: :doc

Use ActiveModel has_secure_password

gem 'bcrypt', '~> 3.1.7'

Use Unicorn as the app server

gem 'unicorn'

Use Capistrano for deployment

gem 'capistrano-rails', group: :development

group :development, :test do
# Call 'byebug' anywhere in the code to stop execution and get a debugger console
gem 'byebug'

# Access an IRB console on exception pages or by using <%= console %> in views
gem 'web-console', '~> 2.0'

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring'
end
```
here is how i have passenger setup in apache:

```
ServerName www.example.com
DocumentRoot /var/www/html/html

Allow from all
Options -MultiViews
# Uncomment this if you're on Apache >= 2.4:
Require all granted
These have been added:

Alias /blog /var/www/html/rails/blog/public
<Location /blog>
    PassengerBaseURI /blog
    PassengerAppRoot /var/www/html/rails/blog
</Location>
<Directory /var/www/html/rails/blog/public>
    Allow from all
    Options -MultiViews
    # Uncomment this if you're on Apache >= 2.4:
    Require all granted
</Directory>
These have been added:

Alias /wordpress /var/www/html/wordpress
<Location /wordpress>


Allow from all
Options -MultiViews
# Uncomment this if you're on Apache >= 2.4:
Require all granted
These have been added:

Alias /testblog /var/www/html/rails/testblog/public
<Location /testblog>
    PassengerBaseURI /testblog
    PassengerAppRoot /var/www/html/rails/testblog
</Location>
<Directory /var/www/html/rails/testblog/public>
    Allow from all
    Options -MultiViews
    # Uncomment this if you're on Apache >= 2.4:
    Require all granted
</Directory>
```
here is the error log from apache:
```
[ 2015-06-15 15:23:10.7045 9008/7f0e9bfff700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 3-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 9cf01f6f. Please see earlier logs for details about the error.
```
Let me know there is any other info that you guys need.

EDIT: fix markdown by @timoschilling

**Comment by souljatechie** [comment]
i apologize in advance for the all the off the wall Markdown.  Didnt realize github did that.

**Comment by timoschilling** [comment]
Does your app starts in the developer mode?

**Comment by souljatechie** [comment]
I have a private dedicated Centos 7 server just for my own pleasure / learning, so i don't really bother going through the whole "est, stage, production" cycle.  I Just do everything on the server through SSH.  I will, however, try dev and stage to see if that makes a difference.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by gmahajan31** [comment]
I am facing the same problem with Passenger and nginx.

Phusion Passenger 5.0.24
Rails 4.2.5
Ruby 2.1.5
activeadmin 1.0.0.pre2


**Here's some logs of the error**

********************************************
[ 2016-02-22 13:28:17.9982 13487/7efe6cfd8700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/xyz/current: An error occurred while starting up the preloader.
  Error ID: df143e67
  Error details saved to: /tmp/passenger-error-3pfW2J.html
  Message from application: There was an error while trying to load the gem '**activeadmin**'. (Bundler::GemRequireError)
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require'
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
  /var/www/accusure/releases/20160222083054/config/application.rb:5:in `<top (required)>'
  /var/www/accusure/releases/20160222083054/config/environment.rb:2:in `require'
  /var/www/accusure/releases/20160222083054/config/environment.rb:2:in `<top (required)>'
  config.ru:1:in `require'
  config.ru:1:in `block in <main>'
  /var/www/accusure/shared/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  /var/www/accusure/shared/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'


[ 2016-02-22 13:28:18.0030 13487/7efe6dfda700 age/Cor/Con/CheckoutSession.cpp:277 ]: [Client 1-2] Cannot checkout session because a spawning error occurred. The identifier of the error is df143e67. Please see earlier logs for details about the error.

********************************************

**I tried to run my app in development and its running fine.**

**Comment by gmahajan31** [comment]
Creating a new issue for this.
