### ISSUE TITLE
Formtastic::UnknownInputError Unable to find input class Input

### ISSUE THREAD

**Issue by mjvezzani** [activeadmin/activeadmin#4178]
Currently experiencing this error `Formtastic::UnknownInputError Unable to find input class Input` while upgrading to rails 4, using Devise and ActiveAdmin.

I've read about the error `Unable to find input class InetInput` here:
https://github.com/justinfrench/formtastic/issues/1115

and here:
https://github.com/activeadmin/activeadmin/issues/3682

In the `ActiveAdmin issue #3682`, the instructions are:
`f.input :inet_field, as: :string # or build you on input type`

My question is in what file is this code change suggestion happening? 

Also, I have not had any success finding anywhere else on the web referencing a `Unable to find input class Input` error. Google returns `No Results Found`. My other question is, is `Unable to find input class Input` a different error from `InetInput`, and if so, what info should I provide to begin debugging this issue?

Thanks!

**Comment by timoschilling** [comment]
Take a look on this files:
https://github.com/justinfrench/formtastic/blob/master/lib/formtastic/inputs/string_input.rb
https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/inputs/datepicker_input.rb
For filter only:
https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/inputs/filters/string_input.rb

Copy and change one of this files and place it in your app under `lib/...`.

**Comment by sandy1987** [comment]
1. mkdir app/inputs/inet_input.rb 
2. put the following code.

class InetInput < Formtastic::Inputs::StringInput
end

**Comment by hugoh1995** [comment]
^^This worked for me as well! Thank you.

**Comment by w-A-L-L-e** [comment]
Yes sandy's hack works and should be done by rails g active_admin:install IMHO! 
Basically the class needs to be there otherwise no edit's and no updates are possible...
Works fine on rails 5.0.6 and activeadmin 1.1.0...
I put this file in /admin, and it works also so I have:

app/admin/admin_user.rb ->scaffolded
app/admin/inet_input.rb -> added to fix the error, with content:

```
#put this in app/admin/inet_input.rb
class InetInput < Formtastic::Inputs::StringInput
end
```

**Comment by oxfist** [comment]
@sandy1987 and @w-A-L-L-e nailed it! Thanks a lot to you both.

I still wonder, what's the reason this works? Is it because ActiveAdmin doesn't know how to treat the columns that contain IP data to a string? I'd really appreciate if anyone could help me understand better.

**Comment by danielricecodes** [comment]
@oxfist - its because Formtastic tries to map certain attribute types to Input Classes.  There's no mapping for `inet` (an IP Address field type that exists in postgresql) to a class in Formtastic.

Perhaps the real fix here is to fork Formtastic and map an Inet type field to the String input.  That would actually solve the problem for everybody with an inet field type in their database, not just ActiveAdmin users.
