### ISSUE TITLE
Associate a readable user

### ISSUE THREAD

**Issue by SylarRuby** [activeadmin/activeadmin#4344]
Can I make this easier to just know the correct user to select?

A user has one company and a company belongs to a user. Is there a way to when the dropdown is pressed, I see their email address?

<img width="482" alt="screen shot 2016-03-13 at 06 04 58" src="https://cloud.githubusercontent.com/assets/7381195/13727224/e67e4936-e8e1-11e5-896a-b61bd4d6a0d9.png">

**Comment by timoschilling** [comment]
Just define a `display_name` on the `User` model.
https://github.com/activeadmin/activeadmin/blob/a252cebb4e6b4939775df2ef6920f16bec38f884/docs/3-index-pages/index-as-table.md#defining-columns

**Comment by SylarRuby** [comment]
Normally you do not put a key on the `User` table, you'd put it on the `Company` table. So `user_id` would be on the `Company` table. The link you gave me was to only add columns. With this gem I need to add a `company_id` on the `User` table for it to pick up the name or email address of the user.

**Comment by timoschilling** [comment]
> The link you gave me was to only add columns.

Not only, it's about how to display a relation, too.

What's your problem?
The fact that you only can see ruby Object representation (`#<User:0x007...>`) in the select instead of the user name? If yes, define a `display_name` method on the `User` model which returns a proper representation as string.
Otherwise provide a better description of your problem.

**Comment by SylarRuby** [comment]
Sorry, @timoschilling. A good early morning coffee understood what you were saying. I did this and all is well:

```

def display_name
  return self.email
end

```
