### ISSUE TITLE
How to move New Resource button on index page

### ISSUE THREAD

**Issue by chrisseldo** [activeadmin/activeadmin#4393]
Hi, 

Was wondering if there's an easy way to move the "New Resource" button over from the rightmost side of the index screen. Ideally, I'd like to move it to the leftmost side of the page.

_Perhaps this is CSS modifcation_ :smile:  

I appreciate any and all insight! 

Best,
Chris

**Comment by timoschilling** [comment]
Can you post a screenshot with a arrow where do you want that button?

**Comment by chrisseldo** [comment]
![image](https://cloud.githubusercontent.com/assets/7948022/14508130/1360346c-0194-11e6-9157-3d5f8f0f5177.png)

**Comment by chrisseldo** [comment]
Hi @timoschilling -- any follow up here? 

I appreciate your help on this 😺 

Best,
Chris

**Comment by dmitry** [comment]
Looks like not easy to do as inside the `titlebar_left` there are a breadcrumb, that will be affected because of the small `titlebar_right` side. Another solution could be change of https://github.com/activeadmin/activeadmin/blob/1c85c5654a2ce1d43d4c64d98b928ff133d46406/lib/active_admin/views/title_bar.rb#L15.

**Comment by timoschilling** [comment]
The only way to do that is to hack the css.
