### ISSUE TITLE
`check_boxes` filter doesn't support `all` compound

### ISSUE THREAD

**Issue by konto-andrzeja** [activeadmin/activeadmin#4559]
I have users with roles, many to many relationship with join table. I try to add filtering users by those roles, but I want to display only users who have all the selected roles (default behaviour is users with any selected role are displayed). Unfortunately, when I use `check_boxes` it doesn't work.

I have this in my `app/admin/user.rb`:
```
filter :role_in_all, as: :check_boxes, collection: proc { Role.all }
```
And this in my `app/models/user.rb`:
```
scope :by_role, lambda { |role_id| joins(:users_roles).where(users_roles: { role_id: role_id }) }

ransacker(
  :roles,
  formatter: proc { |role_id| User.by_role(role_id).pluck(:id) },
  callable: proc { |parent| parent.table[:id] }
)
```

It works when I use `filter :role_in_all, as: :select, multiple: true, collection: proc { Role.all }`, but not for `check_boxes`.

Since `check_boxes` input [adds `_in` to the name](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/inputs/filters/check_boxes_input.rb#L8) what I get is `roles_in_all_in` and `all` compound gets ignored.

When I tried to use custom predicate to force using `in_all` Arel predicate, I got selected checkboxes passed as a string to my validator and formatter (e.g. `"["1","3"]"`). Of course I can parse that to get what I need, but then when it comes to checking which checkbox is selected it fails [here](https://github.com/justinfrench/formtastic/blob/master/lib/formtastic/inputs/check_boxes_input.rb#L141), because it expects array, not a string. Setting predicate type as `:array` doesn't work either.

Is there any way to make it work?

**Comment by timoschilling** [comment]
Your ransacker is shitty!

The `formatter` should format a input (for example downcase or typecast it), not should not select thinks. I know it's a common google / stackoverflow result, but it is wrong!

Don't use your scope in AA.

I don't have the time to provide you a tested solution, but I can point you in the right direction.
Ransack can query across relations, that means you can build a filter like `filter :users_roles_id`, AA will apply this `_in` to it and thats results in `users_roles_id_in`. You don't need to define a ransacker on you model for that. You can test that with `User.ransack(users_roles_id_in: [1, 2]).result`.

Maybe you need to change `collection: proc { Role.all }` to `collection: proc { Role.all.pluck(:name, :id) }`.

Your problem is a ransacker problem, thats why I close this issue, if you have a working ransacker that is tested on the console, but it didn't work on AA, you can come back and I will reopen this issue.
