### ISSUE TITLE
integrate custom search (e.g. Sphinx)

### ISSUE THREAD

**Issue by gingerlime** [activeadmin/activeadmin#4692]
I'm curious if it's possible to integrate a different search "engine" into ActiveAdmin. I understand that filters use Ransack, but if I want to have a more flexible search, how do I integrate it?

I already have search working on some model, and when I run search, it simply returns a bunch of AR objects. What's the best way to tie this together into ActiveAdmin? i.e. can I override the filters? or add a custom search box on the model index page? how do I return the results so they show on the index page? or some other way?

Would appreciate any tips or thoughts on the best way to accomplish this. Thanks!

**Comment by varyonic** [comment]
Seems ambitious.  There are no built in extension points for this.  You could start by looking at https://github.com/activeadmin/activeadmin/blob/master/spec/unit/filters/filter_form_builder_spec.rb and https://github.com/activeadmin/activeadmin/blob/master/spec/unit/resource_controller/data_access_spec.rb  Maybe use a custom action instead of filters for the search and override DataAccess methods to display the results.  http://activeadmin.info/docs/2-resource-customization.html#customizing-resource-retrieval

**Comment by gingerlime** [comment]
Thanks for the pointers, @varyonic ! I'll take a look and see if I can work something out...
