### ISSUE TITLE
Linear-gradient function from Bourbon is deprecated

### ISSUE THREAD

**Issue by mindhalt** [activeadmin/activeadmin#4780]
Linear-gradient function from Bourbon is deprecated. This means that [this](https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/app/assets/stylesheets/active_admin/mixins/_gradients.scss#L4) will generate invalid css rules for BGs.

What options do we have:
1. backport this functions from Bourbon to AA mixins;
2. change function to mixin(```@include linear-gradient(...)```) which still works(for now);
3. update our gradient mixin to use plain css rule.

What say you?
P.S. I can make a PR for preferable method

**Comment by varyonic** [comment]
No strong preference.  I'm guessing 3, 1, 2 if you get no other response.

**Comment by timoschilling** [comment]
@javierjulio what do you think

**Comment by javierjulio** [comment]
@timoschilling that's a native CSS method. It is being used in that manner, it just so happens that Bourbon overrides it as we use SASS. I know this because its setting a fallback background color despite the Bourbon implementation offering that. I would not rely on Bourbon here. We should just silence that warning @mindhalt as the intention is to use the native method. That's the simplest solution. We could easily add the vendor prefix (solution below) but I'd make the argument its useless, the *last* Safari or Chrome browser to *require the vendor prefix* was released back in *late 2012 or Jan 2013* (source: http://caniuse.com/#search=linear-gradient make sure to hit Show All link).

```sass
@mixin gradient($start, $end){
  background-color: $start;
  background-image: -webkit-linear-gradient(top, $start, $end); // Safari 5.1+, Chrome
  background-image: linear-gradient(180deg, $start, $end);
}
```

**Comment by mindhalt** [comment]
@timoschilling @javierjulio 
Also we can use `unquote()` from SASS. In this case Bourbon will not even know that it can override it :)
```scss
@mixin gradient($start, $end) {
  background-color: $start;
  background-image: unquote("linear-gradient(180deg, #{$start}, #{$end})");
}
```

**Comment by mindhalt** [comment]
Made a PR #4791

**Comment by varyonic** [comment]
Of interest? https://github.com/thoughtbot/administrate/pull/789#issuecomment-288821126
