### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by wspurgin** [activeadmin/activeadmin#4925]
I love this framework. It's fantastic, and I use it on a daily basis. The milestone says we're there, but that elusive one dot oh release still escapes us.

What's holding us up? I don't want this issue to be unproductive, but if there are a list of issues or requests still holding up the release, can we document them here? or if they already exist add them to the milestone?

As my own addition, I'll say this: A lot of good work has gone into this release. It was [originally targeted for Rails 4.0 support](https://github.com/activeadmin/activeadmin/milestone/18) and replacing meta-search with ransacker. Now there's Rails 5 support, countless improvements, features, and 5 pre-releases....

Even with that, I'm sure there are things we can do better, features that could be added, and bug fixes, but I, for one, am in favor of using patch and minor releases to publish those things.

Let's craft a plan for a 1.0.0 release (and stick to it) that *doesn't* take 3 more years.

Again, I :heart: ActiveAdmin and I want what's best for it. IMHO that's to start a proper release cycle.

**Comment by deivid-rodriguez** [comment]
Hei! You're not alone, we feel the same way. :)

The current plan is to release 1.0.0 in more or less in sync with Rails 5.1 release.

I've added a couple of tiny bits I think we should sort out before releasing 1.0.0 (or maybe a first rc version) to the 1.0.0 milestone. But we are basically ready. I'm pretty sure all current maintainers are on the same page here, since we've discussed this a lot.

The only problem is that we depend on @timoschilling's availability for releasing which is not a lot. But we're confident he'll find some time to get this done!

Hope this helps.

**Comment by timoschilling** [comment]
@deivid-rodriguez I only waiting for the go from you or one of the others

**Comment by deivid-rodriguez** [comment]
Great, let's get this done then! :muscle:

**Comment by wspurgin** [comment]
Release party 🎉🎉

**Comment by deivid-rodriguez** [comment]
Release is very close now. We should expect a PR bumping version numbers and a push to rubygems soon (ETA: 3 years... :stuck_out_tongue_closed_eyes:).

**Comment by deivid-rodriguez** [comment]
Closed via #4937, congrats to everyone! :tada: :tada: :tada:

**Comment by asecondwill** [comment]
Massive congratulations guys.  activeadmin is awesome.  thanks for all your work.
