### ISSUE TITLE
Support sassc-rails

### ISSUE THREAD

**Issue by swrobel** [activeadmin/activeadmin#5031]
The fact that activeadmin depends on sass-rails causes [conflicts](https://github.com/sass/sassc-rails#installing-alongside-a-gem-that-depends-on-sass-rails) with apps that try to use sassc-rails leading to [complicated](https://github.com/sass/sassc-rails/issues/6#issuecomment-277471795) [workarounds](https://github.com/sass/sassc-rails/issues/68)

**Comment by Fivell** [comment]
possible solution is to require sassc-rails and sass-rails as fallback 

like 
```ruby
begin
  require 'sassc-rails'
rescue LoadError
  require 'sass-rails.'
end
```

**Comment by Fivell** [comment]
@javierjulio , what do you think about it?

**Comment by javierjulio** [comment]
@Fivell I'm not familiar with sassc-rails so I'm not sure what's best. First I've heard of it. What I realized though with this is why do we even require sass-rails as a dependency. I've looked at some other gems like foundation-rails which I use and am thinking perhaps its better for us to require sass as dependency instead? Since ActiveAdmin is only meant for Rails, there won't be any concern since sass-rails is the default and users can decide if they rather use something else. Wouldn't it be better to just replace the dependency with the minimum required and thus we avoid having to require various sass rails based gems to accommodate cases like this?

**Comment by javierjulio** [comment]
@Fivell we require sass-rails here https://github.com/activeadmin/activeadmin/blob/11c1253d2d228cdae27537fff16d75eb091dca69/lib/active_admin.rb#L10 but I wonder why since we don't use it directly. We do have a request spec for stylesheets but I think that's unnecessary. We shouldn't be testing what Rails already tests.

Further I'm not sure why we add our stylesheets and javascripts to the precompile path since we have them in the conventional folders that Rails will just add and compile them for us (from what I understand). For example, reviewing more foundation-rails it [requires smaller dependencies despite using sass based stylesheets](https://github.com/zurb/foundation-rails/blob/master/foundation-rails.gemspec) and also [doesn't do any custom engine stuff for asset precompilation](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/engine.rb#L3-L10).

**Comment by javierjulio** [comment]
I realize now we precompile as users can add their own stylesheets and javascripts too. But even then I wonder if its really necessary? Users can just import/require in the active_admin.scss and active_admin.js file generated.

**Comment by javierjulio** [comment]
@swrobel I've tackled a possible solution with #5037. Could you please give it a try and see if that works for you? Be interested to see how it works out not just locally but in production. Let me know how it goes.
