### ISSUE TITLE
Time zone inconsistency in csv download

### ISSUE THREAD

**Issue by Koos755** [activeadmin/activeadmin#5056]
I have been using active admin in my application and I set the time zone for every request based on the account. This has been working really well.

      #in initializer
      config.prepend_around_action :set_time_zone
    
      # in application controller
      def set_time_zone(&block)
        Time.use_zone(current_account.time_zone, &block)
      end

There is an inconsistency with the CSV downloads where both the filters and the time related fields use the application default time zone not the one set per request. Here is an example for the same record's :create_at

[![created_at in csv][1]][1]

[1]: https://i.stack.imgur.com/lLfOD.png

[![][2]][2]

[2]: https://i.stack.imgur.com/OgChs.png

<br>

This also then creats an inconsistency in the data set on the index page and the csv - if date related filters are applied.

**Comment by taralbass** [comment]
I observed this issue as well and spent some time digging into it. It occurs because the CSV downloads are streamed (except in development) by default, and the `around_action` actually completes and reverts the timezone after the stream is set up but before it is complete. Notably, the timezone reverts before the database query is constructed, as this happens within the `Enumerable` that is set up to handle streaming. I haven't figured out a workaround although I think the code could be reorganized to construct but not trigger the db query earlier. I plan to work around this by simply disabling streaming with the `disable_streaming_in` config option.

**Comment by javierjulio** [comment]
I would accept a PR for resolving this. Thank you.

**Comment by mrhillman** [comment]
Just encountered this with the same scenario described by @taralbass - It's an interesting one.
I didn't want to disable streaming in our instance, as we have large datasets that people export regularly.

For anyone wondering, I monkey-patched the `CSVBuilder` class to specifically include some code setting the time zone (what was in the `around_action`) around the build method. It's ugly but works for us, with lack of a better solution for now
