### ISSUE TITLE
Interest in moving away from coffeescript?

### ISSUE THREAD

**Issue by thejspr** [activeadmin/activeadmin#5101]
Activeadmin is the only gem I use which requires coffeescript, and I was wondering what your guys thoughts are on removing this dependency and migrating all coffeescript to modern vanilla jS? The main benefit I see is less dependencies (I'm not going to start a flamewar about liking coffeescript or not :D)

I'm not sure yet how the resulting JS will look, but before I spike it I'd like to know if the maintainers agree with this direction, otherwise I'll not spend more time on it :)

**Comment by varyonic** [comment]
Dup of #5050

**Comment by javierjulio** [comment]
@thejspr great timing. 😉 We are in agreement. As @varyonic mentioned there is a duplicate issue on seeing about going with ES6 and the reasons for doing so. I've started work in #5081 to convert our existing CoffeeScript into ES6. For now we'll use sprockets-es6 but perhaps before we release AA v2, maybe sass-rails v6 and sprockets v4 will be available meaning [we won't need sprockets-es6 gem](https://github.com/rails/sprockets/blob/master/UPGRADING.md#es6-support).

I'd like to do more work but I think its best and easiest to just convert the CoffeeScript to ES6 and improve the ES6 code afterwards so that way we make sure we provide existing functionality and behavior.

**Comment by javierjulio** [comment]
Please share what thoughts you have on this. I'd love to find help on this too. Once the conversion is in place I want to start removing jQuery UI and use individual components. One commit #5081 shows a quick proof of concept on how that would work. I really like how the JS is done for Bootstrap since they are self contained components and some of them we can use. For other things like date picker, we'll have to find another solution.

Let me know if you have an interest in working together on this and what ideas you had. Thanks!
