### ISSUE TITLE
wrong dependency to rails

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#5209]
### Expected behavior

Active Admin's gemspec didn't specify a dependency to the `rails` gem, which is ok, while for example `inherited_resources` specifies a dependency to `actionpack`.

For this reason I expect that I can use `activeadmin` without using `rails`, I only want to use `actionpack` (the reason is that I don't need actioncable).

### Actual behavior

If I run any command which boots the rails app, I get this error:
```
ActiveAdmin::DependencyError:
  To use rails you need to specify it in your Gemfile.
```

### How to reproduce

Just change a standard Gemfile from
```ruby
gem 'rails'
gem 'activeadmin'
```
to
```ruby
gem 'railties'
gem 'activerecord'
gem 'actionpack'
gem 'actionview'
gem 'actionmailer'
gem 'activejob'
gem 'activeadmin'
```

### How to fix it

This is my current hotfix
```ruby
require 'active_admin/dependency'
module ActiveAdmin
  module Dependency
    class Matcher
      def initialize(name)
        name = 'railties' if name.to_s == 'rails' # should work with 'actionpack' too
        @name = name
      end
    end
    module Adapter
      class Railties < Rails
      end
    end
  end
end
```

**Comment by javierjulio** [comment]
@timoschilling I don't understand why you're doing that. From what I know, to do what you want, you still specify the rails gem as a dependency but instead in `application.rb` replace `require "rails/all"` with explicit requires for the gems you want to use, for example:

```ruby
require "active_record/railtie"
require "action_controller/railtie"
require "action_view/railtie"
require "action_mailer/railtie"
require "active_job/railtie"
```

I bring this up because we too don't use actioncable, at least as of now we don't want to include it until we plan to use it. If I can find the resource as to why I did it this way, I'll share.

**Comment by timoschilling** [comment]
@javierjulio with your way you still need to install `actioncable` and it's dependencies. If we fix the `activeadmin` dependency checking, that's not needed.

**Comment by javierjulio** [comment]
@timoschilling correct but its not loaded. From what I understand that's the way to get around to do what you want. The dependency doesn't change since its still Rails. I'm not sure if its intended to install these gems directly, although of course nothing stopping anyone from doing that. I wanted to share what we were doing since that's how we get around not loading other gems we aren't using which can be very useful.

**Comment by zorab47** [comment]
Any updates here?

**Comment by timoschilling** [comment]
I think this is still a issue, AA's Gemfile defines a dependency to `railties`, but checks that the `rails` gem is used/loaded. Thats bad, AA should check that `railties` is used/loaded!

**Comment by vinnymac** [comment]
@timoschilling thanks for the fix it worked for me 👍

I agree that AA should not assume that one is using the `rails` gem when it is not a dependency of this gem. I only see two courses of action, either make it a dependency or fix it to require `railties` instead of `rails`.
