### ISSUE TITLE
Add items to default_actions column #53

### ISSUE THREAD

**Issue by krtschmr** [activeadmin/activeadmin#5249]
i still can't find a decent solution for  #53 which is 6 years old.
shall we rethink and implement something?

**Comment by wspurgin** [comment]
@krtschmr What's wrong with the solutions in #53? Particularly [this one](https://github.com/activeadmin/activeadmin/issues/53#issuecomment-315285406) that's semi-recent (to the creation of this issue). Per your comment on #53

> This needs work!

What particularly needs work? Like the solution above said (but slightly reworked) if you want some additional action you can send the `actions` method a block:

```ruby
    actions do |some_recrod|
      link_to "Copy", copy_my_admin_record(some_record)
    end
```

In this example, the "Copy" action would be appended to the "View Edit Delete" set of actions. However, as noted in that issue, it only really works when adding *one* action to the default set. If you want to add multiple, then the solution linked above is the only way to do it currently.

I'm all for discussing an adjacent feature here (like if we wanted to configure the global default to *always* add this "Copy" action). However, if you're looking for the same thing as #53 and just a "better" way to do it e.g with some sort of `append_action` method, I think it would be better to keep our discussion there (since then all the conversation is in one place), or at least make this issue more specific. i.e. "Support multiple `link_to`s in the actions DSL" if that's the problem

**Comment by zorab47** [comment]
I'll close this and defer more discussion to #53.
