### ISSUE TITLE
Pagination shown when disabled, but collection size > max_per_page

### ISSUE THREAD

**Issue by emilong** [activeadmin/activeadmin#5260]
### Expected behavior

When `config.paginate = false`, I expected no pagination buttons to be shown regardless of collection size or `max_per_page` configuration.

### Actual behavior

Pagination buttons are shown when the collection size is greater than `max_per_page` even though `config.paginate` is false.

### How to reproduce

This is identical to an existing test case, but with the `max_per_page` set to be less than the collection size explicitly. (Apologies for the long scenario name, I'm not that experienced with best practices for cucumber. :grimacing:)

I was able to get this to fail while the existing one does not with the default `max_per_page = 10_000`.

```cucumber
  Scenario: Viewing index with pagination disabled and a collection larger than max per page
    Given an index configuration of:
    """
      ActiveAdmin.register Post do
        config.paginate = false
        config.max_per_page = 10
      end
    """
    Given 31 posts exist
    When I am on the index page for posts
    Then I should not see pagination
```

**Comment by emilong** [comment]
By way of explanation as to why this is coming up for me, I have a page that displays counts over a collection, but I get pagination when that collection exceeds the `max_per_page` count.

The only reason I set the `max_per_page` count above is to illustrate the error, but you could get the same result with the following test:

```cucumber
  Scenario: Viewing index with pagination disabled and a collection larger than max per page
    Given an index configuration of:
    """
      ActiveAdmin.register Post do
        config.paginate = false
      end
    """
    Given 10001 posts exist
    When I am on the index page for posts
    Then I should not see pagination
```

I'm not suggesting adding this test to the suite though because it added > 2 minutes to create all those objects! :smile: 

The above test also illustrates the bug, but you should probably never use that kind of configuration in practice either. In other words, I'm not sure what kind of test you'd want to add to the suite, but this test is closer to my real scenario.

**Comment by varyonic** [comment]
The first test looks fine: congrats, you are over half way to submitting a PR!

**Comment by littleforest** [comment]
It seems that this is a hard problem to solve, because even if `config.paginate = false`, ActiveAdmin is still using pagination underneath; it is just setting the `per_page` value equal to `max_per_page` [in this method](https://github.com/activeadmin/activeadmin/blob/b45b1fb05af9a7f6c5e2be94f61cf4a5f60ff3bb/lib/active_admin/resource_controller/data_access.rb#L268-L274). So in essence, you still have a paginated collection but it only has one page's worth of data. Truly turning off pagination might be a major undertaking as it would require two flows/templates for displaying paginated vs non-paginated results.
