### ISSUE TITLE
Allow multiple flash messages from the same type

### ISSUE THREAD

**Issue by tiagotex** [activeadmin/activeadmin#5279]
Currently ActiveAdmin only allows to one flash message per type, but sometimes we have the need to show more than one message per type. 

Previously we concatenate strings from multiple alerts but this his hard to read and far from a good UI, so we decided to monkey patch ActiveAdmin to allow multiple flash messages.

In `lib/active_admin/views/pages/base.rb#build_flash_messages `

```ruby
def build_flash_messages
  div class: 'flashes' do
-   flash_messages.each do |type, message|
-     div message, class: "flash flash_#{type}"
+   flash_messages.each do |type, messages|
+     [*messages].each do |message|
+       div message, class: "flash flash_#{type}"
+     end
    end
  end
end
```

This allows us to optionally pass an array to flash.

Would this be a feature that ActiveAdmin should support? If so I can create a PR to add it.

**Comment by varyonic** [comment]
I would hold off on this a little while, I'm working on an [overlapping change](https://github.com/varyonic/activeadmin/commits/layout-refactor).

**Comment by tiagotex** [comment]
Thanks for the reply @varyonic.

I'm still available to implement this change, could you ping me here once your refactoring gets merged?

**Comment by sherbo** [comment]
We need this too. Any update?

**Comment by lrbz** [comment]
Any update on this issue please . thanks

**Comment by mirelon** [comment]
I have submitted a MR: https://github.com/activeadmin/activeadmin/pull/5929, because the overlapping change https://github.com/varyonic/activeadmin/commits/layout-refactor seems to be inactive for a long time.

@theterminalguy I dont understand the `join(' ')` in your proposal. Do you mean you provide a HTML in the message? Or just a link? If you could provide some example input and output in order to create a test...
