### ISSUE TITLE
Undefined method 'inheritance_column' when using non ActiveRecord resource

### ISSUE THREAD

**Issue by tiagotex** [activeadmin/activeadmin#5312]
While updating from ActiveAdmin `1.1` to `1.2` I got an error:

```
NoMethodError: undefined method 'inheritance_column' for MyModel:Class
```

After some research I came across this [issue on activeadmin-mongoid](https://github.com/activeadmin/activeadmin-mongoid/issues/113) that points to a cause and solution in [this PR](https://github.com/activeadmin/activeadmin/pull/5253#discussion_r155525109)

This is caused by using a class (form object) that is not an ActiveRecord resource.

I think it's fine to decide not to support form object by default, but then I would hope we could at least display an error message to better guide people that find this bug.

My preferred solution would be to support form objects as [suggested by @Fivell ](https://github.com/activeadmin/activeadmin/pull/5253#discussion_r155512637) or at least display an error message (explaining the situation and the steps to fix it), what do you think?

As always, I'm available to implement one of the 2 solutions.

**Comment by Fivell** [comment]
@tiagotex 👍

**Comment by faucct** [comment]
It looks like you only need one page with two controller actions: `new` and `create`. What about using `ActiveAdmin.register_page` for it?

**Comment by zaksoup** [comment]
We ran into this exact issue as well. I see [here](https://github.com/activeadmin/activeadmin/pull/5253#discussion_r155525109) you recommend an empty `inheritance_column` method in the class. That felt hacky to us, but if you're recommending it I guess it's not?

I guess what I'm looking for is guidance for the recommended design pattern when building forms in activeadmin that really only need the `new` and `create` action. Should we refactor to use `register_page` instead of what we're currently doing?

Our page, for reference: https://github.com/codeforamerica/clientcomm-rails/blob/develop/app/admin/import_csv.rb

**Comment by faucct** [comment]
@zaksoup, I would suggest something like this:

```
ActiveAdmin.register_page 'ImportCsv' do
  menu false

  controller do
    def index
      if request.get?
        @import_csv = ImportCsv.new
        super
      else
        @import_csv = ImportCsv.new(file: permitted_params[:import_csv][:file].read)

        if @import_csv.save
          redirect_to :admin_client_relationships, notice: 'Clients Created Succesfully'
        else
          super
        end
      end
    end
  end

  content do
    active_admin_form_for @import_csv do |f|
      f.inputs 'Upload CSV' do
        f.input :file, as: :file
      end

      f.actions do
        f.action :submit, label: 'Upload CSV'
        f.action :cancel, url: :admin_client_relationships, label: 'Cancel'
      end
    end
  end
end
```

**Comment by zaksoup** [comment]
Sorry for the extremely late response. Thanks for the example - I consider this question closed on my end.
