### ISSUE TITLE
Destroy errors on nested resources don't create an error flash message

### ISSUE THREAD

**Issue by joker-777** [activeadmin/activeadmin#5369]
### Expected behavior

If a resource has a nested resource which depends on the parent object on destroying

`has_many :nested_resources, :dependent => :destroy`

then active admin should show an error message too.

### Actual behavior

Active admin shows a positive destroy flash message but the object is actually not destroyed.

### How to reproduce

Have two models with the `has_many` relationship where the parent destroys the children automatically.
Have some validations in the children model which fail when you try to destroy the parent object.
This error case will not be shown to the user as a flash message but instead, a positive message is shown.

### Nice to have

The concrete error messages should be shown in the flash message. Right now only a generic error message is shown as a flash message when the parent object has error messages.

**Comment by domangi** [comment]
This is due to the fact that when an association prevents the destroy, normally by throw(:abort), the error message is written only on the association object itself, while the errors array of the object you are trying to delete remains empty.

``` ruby

class Post < ActiveRecord::Base
   ...
   has_many :taggings, dependent: :destroy
end

class Tagging < ActiveRecord::Base
  ...
  belongs_to :post
  before_destroy do
    self.errors.add(:base, "Tagging cannot be deleted")
    throw(:abort)
  end
end
``` 

Assume you have a post object with an associated tagging, when you try to destroy the post object it will be prevented by the before_destroy callback in the tagging object, but only the tagging object errors will have an entry, while the post object errors messages will be empty, and active admin will show a success message even if the object was non deleted.

To fix this problem you have to ensure that there is an error message in the object your try to delete. You can do it manually in your associated object before throwing abort, in the example above it would be something like this:

``` ruby
class Tagging < ActiveRecord::Base
  ...
  belongs_to :post
  before_destroy do
    self.post.errors.add(:base, "Tagging cannot be deleted")
    throw(:abort)
  end
end
``` 

Or you can override the destroy method in active_admin in order to check if the destroy method was successful, and add an error message if it failed:

``` ruby
# lib/destroy_action_monkey_patch.rb
module ActiveAdmin
  class ResourceController < BaseController
    module DataAccess
      def destroy_resource(object)
        run_destroy_callbacks object do
          if object.destroy
            true
          else
            object.errors.add(:base, "Not destroyed") if object.errors.empty?
            false
          end
        end
      end
    end
  end
end
```

I prefer this method because IMHO if the destroy fails then it should never say "successfully destroyed..."

In this [gist](https://gist.github.com/domangi/b6c5a7fcab1fd5f82d5844fd841f76f1) you find 2 files that override the single destroy method (destroy_action_monkey_patch.rb) and the batch destroy method (batch_destroy_monkey_patch.rb), that need to be placed in your lib folder and required in your active_admin initializer (active_admin.rb)

I also pushed a branch with these patches (https://github.com/domangi/activeadmin/tree/5369-destroy-errors-on-nested-resources), but I have to implement some tests before sending a pull request.

@joker-777 hope this is useful for you ;-)

**Comment by joker-777** [comment]
Hi, Thanks for your long explanation. I'm wondering if it also possible to iterate of all relations and check for any errors or maybe even use `destroy!` which I think fails when children have errors.

**Comment by domangi** [comment]
Yes, you can iterate through the model associations using the [reflect_on_all_associations](http://api.rubyonrails.org/classes/ActiveRecord/Reflection/ClassMethods.html#method-i-reflect_on_all_associations) methods.

I didn't understand exactly what you are trying to do, but you could use this to show the error messages of the associated objects. In this case you need only to check the associations which have the "dependent: destroy" option.

The destroy_action_monkey_patch.rb that shows association error flash messages would look something like this:

```ruby
#lib/destroy_action_monkey_patch.rb
module ActiveAdmin
  class ResourceController < BaseController
    module DataAccess
      def destroy_resource(object)
        run_destroy_callbacks object do
          if object.destroy
            true
          else
            # get all has_many associations configured with dependent destroy
            associations = object.class.reflect_on_all_associations(:has_many).select{ |association| association.options[:dependent] }
            # get association names
            assocation_names = associations.collect{|association| association.name}
            # check each association for errors that prevented destroy
            assocation_names.each do |association|
              objects = object.send(association)
              objects.each do |obj|
                # add each error message to the objects base error messages
                obj.errors.full_messages.each{|message| object.errors.add(:base, message)}
              end
            end
            flash[:alert] = object.errors.full_messages.join(". ").html_safe
            false
          end
        end
      end
    end
  end
end
```

It is not very elegant, but it does the job ;)

**Comment by joker-777** [comment]
Thanks a lot for the snippet. Good to know that this is also possible.
What about the other option to use `destroy!` in active admin and then catching the error? I'm not 100% sure but I think it also breaks when associations have errors

**Comment by domangi** [comment]
If you use `destroy!` then a RecordNotDestroy Exception is thrown if the object.destroy returns false, like described [here](https://apidock.com/rails/ActiveRecord/Persistence/destroy%21)
This means it will throw the exception also if the reason the object fails to destroy is inside an association.
