### ISSUE TITLE
Only show form input fields in permit_params

### ISSUE THREAD

**Issue by yagudaev** [activeadmin/activeadmin#5390]
### Expected behavior

Specifying a resource with no `form` block should only show fields listed in `permit_params` instead of showing all fields and not being able to save the record.

e.g.

```ruby
ActiveAdmin.register User do
  permit_params :email
end

# /admin/users/1/edit

# should ONLY show `email` field. i.e same as specifying:

form do |f|
  f.inputs do
    f.input :email
  end

  f.actions
end
```

### Actual behavior

It shows all the fields available on the model. Trying to save the user would hit an error.

### How to reproduce

See above

**Comment by Fivell** [comment]
related https://github.com/activeadmin/activeadmin/issues/3236 and
https://github.com/activeadmin/activeadmin/issues/3308

**Comment by vishthemenon** [comment]
I think this is a really old issue which a hasn't been resolved in a while. Looking through the other issues it seems like there are 2 approaches to this.

1. Create a "sharp knife" - `permit_all_params` method
2. Change how the default form detects the permitted params and generates the inputs

I am in favour for 2.

**Comment by Fivell** [comment]
this is right line to fix imo https://github.com/activeadmin/activeadmin/blob/9541d9a33679d247c084ea87e62b63504aa79fda/lib/active_admin/views/pages/form.rb#L45

**Comment by yagudaev** [comment]
I agree, would be nice to see a PR for this. Sadly got no bandwidth for it lately.

**Comment by mapeveri** [comment]
Hello, I would like to take this issue and send a PR, although I was looking at the lines that @Fivell comments and I can not understand how the form is generated with the default values. Could you explain me a little more? Thank you.

**Comment by marclerodrigues** [comment]
Hey guys! I've created a PR implementing this feature. Please, take a look.

**Comment by javierjulio** [comment]
Personally, I'm not a fan of ActiveAdmin dynamically generating the form. Taking on all the possibilities for permitted params and how to generate the form from that, I think is too much. It's just simpler to define the form as is with other page actions. If a proposal can come forward that actually demonstrates how to handle the many possibilities with permitted params then we can review. Otherwise, these kind of features I believe introduce either side effects or other configuration requests since users don't want to declare the form to customize.
