### ISSUE TITLE
CSV Export columns for associations

### ISSUE THREAD

**Issue by SxDx** [activeadmin/activeadmin#5459]
### Setup

```ruby
class Magazine
  has_many :order_lines
  has_many :orders, through: :order_lines
end

class OrderLine
  belongs_to :magazine
  belongs_to :order
end

class Order
  has_many :order_lines
  has_many :magazines, through: :order_lines
end
````

### Expected behavior
Something like this:
```ruby
ActiveAdMin.register Order do
  csv do
    column :id
    order.order_lines.each do |order_line|
      column order_line.magazine.name, &:quantity
    end
end
```
### Actual behavior
Currently we have to use the following workaround

```ruby
ActiveAdmin.register Order do
  csv do
    column :id
    Magazine.all.each do |magazine|
     column magazine.name do |order|
       order_line = order.order_lines.find_by(magazine_id: magazine.id)
       order_line ? order_line.quantity : 0
     end
   end
end
```

I feel like this could be a very common use case, am I missing the obvious solution here?
AFAIK there is no way to get the current instance in the csv block, only `@collection` is available and there is no csv equivalent to `table_for` which is available in the show block.

I know this may not possible at all because you pretty much have to know the number of columns as well as the column headers beforehand.

**Comment by chumakoff** [comment]
You can't create a table based on a single record instance because the columns set has to be the same for all records. 

In your case the expression `order.order_lines` might return different number of items for each `order`. How do you expect to build the table header (the set of columns) this way? It doesn't make sense.

The workaround (so called) you use seems to be the only right solution in your case. The number of columns is the same for all `orders` and is equal to the number of `magazines`.

If you want to filter out `magazines` that are not associated with any `order` in the collection and you have the access to the collection on that level, you can do something like this:

```
csv do
  column :id
  
  # fetch only `magazine`s that are associated with the current `orders` scope
  Magazine.joins(:orders).merge(collection).each do |magazine|
   column magazine.name do |order|
     order_line = order.order_lines.find_by(magazine_id: magazine.id)
     order_line ? order_line.quantity : 0
  end
end
```
