### ISSUE TITLE
Why jQuery? 

### ISSUE THREAD

**Issue by colinrubbert** [activeadmin/activeadmin#5618]
I've been looking into using ActiveAdmin for one of my applications that I'm working on but what I can't understand is exactly why jQuery is being used?

What purpose does it serve? 

Why not just use Vanilla JS and have people use jQuery IF they need it? I can't see anything other than datetime translation to a more human readable form. I can't see any other jQuery usage in the gem/app.

Could someone explain what the use case is for this? I can understand using jQuery for legacy browser support but that's a relatively small portion of active browser use these days. Seems like a bloated addition for modern browsers.

**Comment by javierjulio** [comment]
@colinrubbert if you consider when ActiveAdmin was created, it will make a lot more sense why jQuery is used. As far as actual code, jQuery is used in most if not all our javascript files.

**Comment by colinrubbert** [comment]
@javierjulio I understand the ecosystem when ActiveAdmin was created, however, we shouldn't lock ourselves into that ecosystem just because of "that's how things were back then" attitude. 

I would think modernization and support would be an excellent way to advancing the gem and allowing more design freedom for people who want to use it.

There's no doubt that there would be some re-writing of the JS related code but that could help performance and a reduction in dependencies to other software. If someone would want to use jQuery features then they can add them. 

While jQuery is still used by many people it's starting to lose it's original purpose with the consolidation of vanilla JS and it's ease of use now (this from someone who HATES anything JS related 😆).

**Comment by javierjulio** [comment]
We do because we need to maintain this. To rewrite without jQuery would be a huge effort. We would have to replicate key functionality ourselves or introduce some smaller libraries that do specific things like event handling. While it is doable some tasks are quite challenging. You're more than welcome to give it a try! It wouldn't hurt. We have test cases so you can see what you can tackle, fail and then get to pass.

**Comment by chevinbrown** [comment]
I’m not super familiar, but I browsed through the assets and it appears the largest reliance is upon either jQuery ui or various plugins? 
Would it be worth making an initiative to move away from jQuery? That is, a slow progressive move away? Or is that level of effort just not worth it?

**Comment by javierjulio** [comment]
@chevinbrown I don't think it's worth the effort at the moment. Personally, I think it would be more worthwhile to do 2 major things: use a CSS framework such as Bootstrap and replace Formtastic with SimpleForm (or something else). Of course using something like Bootstrap would still use jQuery but there could be another option that does not. I don't think jQuery is the problem here. It helps others that use AA if they need to create their own JS components they can do so quite easily by learning something with a good API and documented rather than a mish mash of libraries.

**Comment by javierjulio** [comment]
@chevinbrown you aren't digressing. It's really all linked/related so its good to discuss. The reason is that we have to support the DSL we have now for outputting not just form controls, but their HTML wrappers and such for layout. That's why I suggest SimpleForm since it does this already. We'd have to create our own if not. There could be other libraries but I'm not aware of any.

I like Tailwind too and the push for functional CSS. It does it right by not forcing pure functional style but allowing you to extract common styles as they appear into classes. I think AA though would benefit more from a CSS framework in place as we'd need many components that are already part of one. That's why I suggest something like Bootstrap.

**Comment by varyonic** [comment]
See #5048

**Comment by danielricecodes** [comment]
> use a CSS framework such as Bootstrap and replace Formtastic with SimpleForm (or something else).

:100: 

Most of my apps have SimpleForm and Formtastic in the bundle...and I only have Formtastic b/c its an ActiveAdmin dependency.

**Comment by tobsch** [comment]
Hey! I just came across this as I wanted to propose the same as @chevinbrown: Migrating to a better CSS setup like Tailwind so that it's easier to extend the views.

Honestly, I tried sooo many alternatives to active admin (forest, ...) and just bounce back all the time as I love it and it just gives you more freedom.
The only thing that most developers got a bit bored of is the looks (+ a few features). 
I'd love to if activeadmin in the future would be built on top of tailwind + potentially tailwind-ui AND I think AA should change the default theme soon. I would actually sponsor it with my company if that helps...

**Comment by garethfr** [comment]
@tobsch I'm sure that for every person who would prefer tailwind, there is another that is using bootstrap, or vanilla CSS. You can't please everyone.

Having said that I'm trying to remove jQuery from my app and activeadmin is the last remaining dependency.

I'm sure that jQuery made sense 5 or 10 years ago. I'm wondering if it still makes as much sense considering widespread adoption of ES6 now.

**Comment by javierjulio** [comment]
Just to follow up, on the default branch we've already migrated to Tailwind CSS and have removed jQuery and jQuery UI. Lots of major changes. This is all in the works for a v4 release.

**Comment by stephenhighemprise** [comment]
@javierjulio Do you feel like the default branch is stable enough for a client project right now?

**Comment by javierjulio** [comment]
@stephenhighemprise depends. Would this be a new implementation or updating an existing one? If you haven't contributed before, I'd suggest going through the Contributing guide to run a dev app locally (auto generated). This way you can try out the various changes there.

The main issue, is I haven't added or updated the generator commands. We need new ones to recreate the config initializer (many configs have been removed) and to generate the new asset files. The expectation is that the host app will run cssbundling-rails and importmap-rails but through partials they can choose their own asset approach. My plan is to cut a beta release to start. Breaking changes can still be expected though.

If this is updating an existing ActiveAdmin setup, I'd recommend reviewing the initial Upgrading docs in #8182 to give you an idea of what's coming. Happy to chat through email and offline if it helps. Looking for feedback. Thanks!

**Comment by stephenhighemprise** [comment]
@javierjulio New project.  It sounds like it might be smoother sailing to wait for the new release to get the benefits of the next version.  Thanks for all your hard work!

**Comment by javierjulio** [comment]
@stephenhighemprise it should be easier with a new project. I recommend reviewing the Upgrading guide in the repo which I merged in earlier. It has the updated generator commands as well. I will be releasing v4 beta1 this weekend. Any help or feedback would be much appreciated. I've only been testing within my own projects but so far so good.

**Comment by javierjulio** [comment]
@stephenhighemprise just released the v4 beta.
