### ISSUE TITLE
Index table too wide

### ISSUE THREAD

**Issue by Quintasan** [activeadmin/activeadmin#5668]
### Expected behavior

Index table and filter section should fit on screen

### Actual behavior

Filters section gets pushed out of screen

![screenshot_20190123_154713](https://user-images.githubusercontent.com/6539261/51614554-2e72bb00-1f26-11e9-9526-220d3e425460.png)

Note the scrollbar and the bottom

### How to reproduce

I created a Rails 5 application mostly according to https://blog.heroku.com/a-rock-solid-modern-web-stack. I didn't generate my application with `--api` switch. I also added a Survey model with a lot of columns. Some of them are hidden in the screenshot

**Comment by deivid-rodriguez** [comment]
What should we do instead? Reserve a specific width percentage for the filters and deal with horizontal spacing issues inside the index table instead (horizontal scrolling? content wrapping?)? I'm really not sure. @javierjulio?

**Comment by javierjulio** [comment]
We could do various things here which is why I don't consider it a bug. It's simply a default but we can change that if we want. I haven't looked at this for a long time but I know when I last did, I came to the conclusion its fine as a default because it depends on what we want to do not just for the table but for the page as a whole. For example, they don't have to be side by side, the filters could be in a collapsible area above the index table (this is something I've seen in other admin tools) which is quite handy and tidy. It could also be collapsible but still remain on the side too. You could also make the table horizontally scrollable but it might not be clear that it is (it's doable/serviceable though). There are other options we could come up with.

Some small wins could be with just changing the CSS. For example, in the screenshot provided, some table column headers are very long because they don't wrap. We could remove that so they wrap to fit and make sure its vertically aligned to the bottom.

At some point it's simply going to break with too many columns in a view. There is only so much we can do that I think its best to have a simple default (doesn't have to be the one we have currently) and let users change to suit their needs.

**Comment by Quintasan** [comment]
@Fivell Thanks, this kind of alleviates the problem since the filters are visible no matter how many columns I have :D

@javierjulio I think `rails_admin` opted for the horizontal scrolling and I think it looks quite self-explanatory

![image](https://user-images.githubusercontent.com/6539261/52265308-0f1b5b00-2934-11e9-8b64-cc6f2b6ba81b.png)

**Comment by amazing-jay** [comment]
Can anyone here help me figure out the CSS required to make the table fit to screen (minus filter area) with horizontal scrollbar? I've tried all the following, but nothing is working. I've also included https://github.com/activeadmin-plugins/active_admin_sidebar for its collapsable features (but am not married to the gem). The reason I want fit to screen is because without it the new <resource> button and logout button are not immediately available to the user.

**Comment by amazing-jay** [comment]
@javierjulio do you have any thoughts? The reason I want fit to screen is because without it the new button and logout button are not immediately available to the user under the default behavior.

**Comment by javierjulio** [comment]
@amazing-jay I don't see anyway to achieve that without significant work. You can only do so much before too much content will just not fit. The most I can offer is what I've done in #3862 where the header remains within the viewport, but the table/filters, if they have too much content, they scroll offscreen.

Since at work we use the #3862 fork, I don't have the original CSS but I fooled around with the demo and to at least mimic what I did there, all you should need is the following considering that:

```css
.index #wrapper {
  display: block;
}

#active_admin_content {
  display: table;
  width: 100%;
}
```

The first selector was originally set to `display: table;` which causes the header to go offscreen too which is why you don't see the buttons New, Logout, etc.

**Comment by amazing-jay** [comment]
Thanks @javierjulio! Although you said it couldn't be done your code helped tremendously:) I needed the .index #wrapper directive to make things play normal. Here's what I ended up with. You're the best:
`.index #wrapper {
  display: block;
}

.paginated_collection_contents {
  overflow: scroll;
  width: 100%;
}`

**Comment by rylanb** [comment]
SCSS that worked for me for this if anyone comes after me. I'm not 100% sure if this covers all scenarios, but works for the index pages I've looked at. 

`calc 100%-300px` is for the 270px width of the side par and a ~30px margin.

```
body.active_admin {
  &.index #wrapper {
    display: block;
  }
  #active_admin_content {
    width: 100%;
    .left_sidebar {
      #main_content_wrapper {
        width: 100% !important;
      }
    }
  }
  #main_content {
    width: 100%;
  }
  #collection_selection {
    width: 100%;
  }
  .index_content {
    width: 100%;
  }
  div.index_as_table {
    max-width: calc(100% - 300px);
    overflow-x: auto;
    width: 100%;
  }
}
```

Test it out if you find this.

**Comment by jmschp** [comment]
This is what worked for me, to have a horizontal scroll when the table does not fit in screen.

I also added a `white-space: nowrap;` So it wouldn't warp the text in each row.I think it looks much better, but it can make thing quite wide!

```scss
body.index.active_admin {
  #wrapper {
    display: block;
  }
  .index_content {
    .index_as_table {
      width: 100%;
      overflow-x: auto;
    }
  }
}

.index_as_table {
  table.index_table.index {
    th {
      white-space: nowrap;
    }
    td {
      white-space: nowrap;
    }
  }
}
```

- Ruby 2.7.4
- Rails 6.1.3.2
- Active Admin 2.9.0
