### ISSUE TITLE
Date Range fields broken after 2.5.0 release

### ISSUE THREAD

**Issue by kivanio** [activeadmin/activeadmin#5955]
### Expected behavior

Date Range fields broken after 2.5.0 release.
I believe that is related to https://github.com/activeadmin/activeadmin/pull/5867

If you configure:
<pre>
filter :month, as: :date_range
</pre>

Before 2.5.0 it creates the following html:
`<div class="date_range input optional stringish filter_form_field filter_date_range" id="q_month_input"><label class="label">Mês</label>
<input size="12" class="datepicker hasDatepicker" maxlength="10" placeholder="De" value="" type="text" name="q[month_gteq]"  id="q_month_gteq">
<input size="12" class="datepicker hasDatepicker" maxlength="10" placeholder="Até" value="" type="text" name="q[month_lteq]"  id="q_month_lteq"></div>`

id="q_month_gteq"
id="q_month_lteq"

After 2.5.0:
`<div class="date_range input optional stringish filter_form_field filter_date_range" id="q_month_input"><label for="q_month" class="label">Mês</label>
<input class="datepicker hasDatepicker" value=""  id="q_month"  type="text" name="q[month_gteq]">
<input class="datepicker hasDatepicker" value="" id="q_month"  type="text" name="q[month_lteq]"></div>`

id="q_month"
id="q_month"

### Actual behavior

The date picker does not work anymore because the IDs now are equal in both range fields.
And also it lost other html options like placeholder, maxlength.

All my date/datetime fields are broken like this example.

**Comment by deivid-rodriguez** [comment]
Thanks for reporting this, I'll have a look at this ASAP.

**Comment by deivid-rodriguez** [comment]
Pinging @mirelon just in case you have any ideas.

**Comment by mirelon** [comment]
The problem is that #5867 calls input_html_options which uses `Formtastic::Inputs::Base` methods to generate option keys (id, placeholder, maxlength, size, required, autofocus, readonly).
The result is the duplication of id for both inputs (and other wrong options).
DateRangeInput is special, because for one input it generates two separate inputs (is there any other input, which consists of multiple sub-inputs?). It cannot use default Formtastic options and override DateRangeInput's default options and propagate them to all sub-inputs.
I suggest overriding default options not by calling Formtastic's input_html_options, but by calling `(options[:input_html] || {})`. In this way the programmer still can override options. The missing options are filled by ActionView in render method.
