### ISSUE TITLE
Migration Guide from 1.x to a 2.x

### ISSUE THREAD

**Issue by poloka** [activeadmin/activeadmin#5971]
I wanted to ask if a migration guide was created for going from a 1.4.3 version to a 2.x version?  If there is no migration guide, what non-passive changes were introduced that caused the 2.x version bump?

**Comment by deivid-rodriguez** [comment]
Hi @poloka, thanks for your question.

ActiveAdmin 2.0 should be essentially 100% compatible with ActiveAdmin 1.0. We took a very conservative approach when bumping the major version because we dropped the `coffeescript` dependency and found that in real life, some applications were using `coffeescript` but actually depending on it through the (indirect) dependency provided by ActiveAdmin. So, even ActiveAdmin was not to be blamed, they would break with the 1.x -> 2.x bump. Maybe it was not the right call, but that's how we did it.

Anyways, you should normally expect a flawless upgrade, but don't forget to have a strong test suite, test your changes on a staging environment first, and all of the other good practices for upgrading things :)
