### ISSUE TITLE
Action Text support on Rails 6.0

### ISSUE THREAD

**Issue by yopaz-giapnh** [activeadmin/activeadmin#6106]
`Action Text` is one of the most awesome feature that introduced in Rails 6.0. But I could not use the `Action Text` with `Active Admin`. Does `Active Admin` itself support it? If doesn't, please consider to support the function in the near feature.

**Comment by nayadd** [comment]
Any news on this one? I found several different ways to implement this, but would love official support from the gem!

**Comment by deivid-rodriguez** [comment]
Hi, no, sorry! I never used `Action Text` myself. Any links to guides on how to set it up, how to use it, and how you would like it supported in ActiveAdmin would be appreciated. Thanks!

**Comment by troya2** [comment]
There's a SO article on integrating it with Active Admin (links to this issue, actually).
https://stackoverflow.com/questions/57879823/how-do-i-use-rails-6-actiontext-fields-in-an-activeadmin-form-block

**Comment by MaximeRobion** [comment]
Hey, @deivid-rodriguez Action Text is really nice to use to be fair. You can read about it here: https://edgeguides.rubyonrails.org/action_text_overview.html.

It is a really quick setup and goes well in hand with [Active Storage](https://edgeguides.rubyonrails.org/active_storage_overview.html). The story is that it started as an open-source project from the dev team at Basecamp ([see the project page here](https://trix-editor.org/)), and worked so well that they integrated it in Rails 6.0.

2 things which would be really nice with an active admin integration would be : 
- the display of rich text in the index view. At the moment, active admin renders `body` so you can't get the information right away about what was written in the field. (see picture)
<img width="746" alt="screenshot" src="https://user-images.githubusercontent.com/53403439/99915730-b46c1280-2d05-11eb-8c71-a988464ab1df.png">

- The form integration for creation and edition of a rich text area. At the moment, this is what you get in the edit form for instance : 
<img width="1049" alt="Capture d’écran 2020-11-22 à 20 58 59" src="https://user-images.githubusercontent.com/53403439/99915822-44aa5780-2d06-11eb-8e2c-121efc59f451.png">
Since trix editor/action text create a new div called trix-content, the edition in Active Admin become particularly tricky. 

Cheers and thanks for the great work you do!

**Comment by johnnncodes** [comment]
+1 for adding support for Action Text

**Comment by TylerSangster** [comment]
+1

**Comment by matthewblack** [comment]
+1

**Comment by alfuken** [comment]
2 years, no news? Huh...

**Comment by giapnhdev** [comment]
@alfuken how many likes should I get before this issue become in progress :)))

**Comment by alfuken** [comment]
> @alfuken how many likes should I get before this issue become in progress :)))

dunno, but you got mine! 👍  ;)

**Comment by javierjulio** [comment]
We have someone on the team that has already expressed an interest in this so we'll try to address this separately, thank you. On the default branch we've migrated to TailwindCSS and removed SASS for v4.

**Comment by alexanderadam** [comment]
> We have someone on the team that has already expressed an interest in this so we'll try to address this separately, thank you. 

Would you mind to elaborate on this? I guess the solutions from the original issue requesting rich text possibilities from 2018 won't work any more and for me it's not quite clear what "addressing separately" means.

Is there yet another issue to track or won't this be implemented now? :thinking: 
Did "someone on the team" implement this in the default branch?

If so, is there any issue where this feature can be tracked? :thinking: 

Or is there any other rich text possibility right now?

**Comment by Skulli** [comment]
It worked for me a while back but attachment storage via form does not any more. Any ideas? But maybe we have to wait until version 4.

**Comment by Olzhassss** [comment]
@alexanderadam There's [Quill](https://github.com/blocknotes/activeadmin_quill_editor) as an alternative

But I made Trix work by adding Trix's JS and CSS to ActiveAdmin's JS and CSS (AA version 4). I can elaborate if you need
