### ISSUE TITLE
Support scopes with a dynamic label and a scope block

### ISSUE THREAD

**Issue by abdelrahmanabdelnabi** [activeadmin/activeadmin#6194]
Active admin scopes don't support scopes with a dynamic label (a proc) and a block for the scope at the same time. I can either have a scope with a dynamic label and a predefined scope on the model or a scope with a static label and block for the scope.

Example of what I tried to do:
```
scope -> { I18n.t('admin.scopes.assigned_to_me') } do |scope|
  scope.where(assignee: current_admin_user)
end
```
However this results in:
`A string/symbol is required as the second argument if your label is a proc.`
which is caused by [this line](https://github.com/activeadmin/activeadmin/blob/8afc4175e19f067b199c6d1249aa302ddab09349/lib/active_admin/scope.rb#L35).

Also I tried using the `localizer` option since all I want is just to translate the scope name but it failed to find the translation since I have it defined under `admin.scopes` not under `scopes`. This is because we have our page registered under a namespace but active admin [doesn't use the namespace when looking for the translation](https://github.com/activeadmin/activeadmin/blob/8afc4175e19f067b199c6d1249aa302ddab09349/lib/active_admin/scope.rb#L58).

Here is how I a registering my resource:
```
ActiveAdmin.register(CoreEngine::CRM::ActivityEvent,
                     as: 'event',
                     namespace: :admin) do
 # some code
end
```

I think active admin should look for the scopes translations under the namespace if the model is registered in a namespace.

**Comment by javierjulio** [comment]
I would accept a PR for this. Thank you.

**Comment by mgrunberg** [comment]
@abdelrahmanabdelnabi, `localizer` supports two ways to define the scope label: global and per resource. 

Example:

```yml
# config/locales/en.yml
en:
  active_admin:
    scopes:
      all: "This is a global translation"
    resources:
      post:
        scopes:
          all: "This only applies to posts"
```

In your case, the resource key is something like `core_engine/crm/activity_event`. Please don't take it literally because the value depends on your infector setup. To get the real value you can run `CoreEngine::CRM::ActivityEvent.model_name.i18n_key` in a console.

Isn't the resource form not enough? Do you have the same resource in two namespaces and want different translations on each namespace?

It is possible to add namespace to localizer translation lookup, but I prefer not to do it unless there is a real use case.
