### ISSUE TITLE
RadioInput for filters

### ISSUE THREAD

**Issue by glv** [activeadmin/activeadmin#6247]
There is at least one legitimate use case for supporting a radiobutton group as a filter.

We encountered a situation where we wanted two sets of scopes that would compose, rather than simply being used for visual grouping. That idea's just a poor fit for ActiveAdmin, but I was able to implement the subsidiary scope group as a filter. But it didn't feel right as a select; as another fixed, low-cardinality set of options, it seemed like a better UX to have them all visible all the time, as with scopes. Similarly, it wasn't right for checkboxes, because it wouldn't make sense to choose more than one option at a time.

Having the options displayed this way met our needs pretty well. If this seems like a good fit for ActiveAdmin, I'd be interested in taking our code for this, adding tests and docs, and submitting a PR.

![image](https://user-images.githubusercontent.com/959/82742824-2f894780-9d28-11ea-9a9c-a10de12d7678.png)

**Comment by erotenberg1** [comment]
+1

**Comment by javierjulio** [comment]
I haven't had a need for this or see much value over a drop down. No issue with having this as a feature. My main concern would be with this, how would the defaults be affected. I think as this is just opt-in that would be ok. I'm not seeing much pressing need for this though since it's not any different over drop downs. If others are interested though a PR can be opened. Thank you.
