### ISSUE TITLE
multiple default sort_order

### ISSUE THREAD

**Issue by ghost** [activeadmin/activeadmin#659]
``` ruby
  config.sort_order = [:visible_desc, :name_asc]
```

should be supported. please mark as a feature

**Comment by crystalneth** [comment]
I found a hack for this. Not sure why config.sort_order doesn't just accept SQL, however setting it to empty string seems to allow the scoped_collection order to be passed through.

  controller do
    def scoped_collection
        Model.all.order('foo ASC, bar DESC')
    end
  end

  config.sort_order = ''

**Comment by seanlinsley** [comment]
@crystalneth we don't support raw SQL because it requires work to make sure that we don't introduce SQL injection vulnerabilities. If you're willing to work on a PR for this, I'd be happy to answer any questions you have.

**Comment by brightbytes-dude** [comment]
@crystalneth - Unfortunately, setting `config.sort_order = ''` no longer works to preserve the order provided in `scoped_collection` in AA 2.9.

Any other ideas for how to do a customer sort order?

(I need it for a `DISTINCT ON` query, but I don't want to over-ride `def index` because then I can't use filters (... though there may be a hack-around for that too ...)
