### ISSUE TITLE
NoMethodError: undefined method 'to_i'

### ISSUE THREAD

**Issue by HanyMoh** [activeadmin/activeadmin#6613]
NoMethodError
undefined method `to_i' for #<ActiveAdmin::Application:0x00007fc8d037e880>
Did you mean?  to_s

vendor/bundle/ruby/2.7.0/gems/activeadmin-2.8.1/lib/active_admin/application.rb in method_missing at line 36

```  
  devise_for :users
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) # <<<< ERROR HERE
  
  get 'messages/index'
  get 'messages/show'
```

**Comment by ball-hayden** [comment]
In our case, this was caused by `sentry-raven` (although the same issue with exist with `sentry-rails`).

 ActiveAdmin publishes `ActiveSupport::Notifications` with different to Rails. Sentry assumes that the second argument is a time, while ActiveAdmin instead provides the application.

I've worked around this with the following monkeypatch:

```rb
# config/initializers/sentry_active_admin.rb

require "raven/breadcrumbs/active_support_logger"

module RavenActiveAdminMonkeyPatch
  def self.prepended(base)
    class << base
      prepend ClassMethods
    end
  end

  module ClassMethods
    def add(_name, started, _finished, _unique_id, data)
      return if started.is_a? ActiveAdmin::Application
      return if started.is_a? ActiveAdmin::Namespace
      return if started.is_a? ActiveAdmin::Resource

      super
    end
  end
end

Raven::Breadcrumbs::ActiveSupportLogger.prepend RavenActiveAdminMonkeyPatch
```
