### ISSUE TITLE
Missing global per_page setting

### ISSUE THREAD

**Issue by heaven** [activeadmin/activeadmin#6861]
Per page setting exist only in the `register` DSL but missing in configuration, which requires a huge amount of copy-pasting.

**Comment by ParthivSavani** [comment]
@heaven add `config.default_per_page = 10` in /config/initializers/active_admin.rb file and check.

**Comment by heaven** [comment]
Hi @ParthivSavani, I was mentioning this setting `per_page = [10, 30, 50, 100]`

**Comment by deivid-rodriguez** [comment]
Hi @heaven!

As @ParthivSavani mentioned this is implemented by the `default_per_page` config, so `config.default_per_page = [10, 30, 50, 100]` should do the trick for you.

I can see how this could be confusing because the name of the per resource configuration doesn't match the name of the global configuration. Maybe we could introduce the `per_page` setting and deprecate `default_per_page`.

**Comment by heaven** [comment]
Hi @deivid-rodriguez, yeah, we do use `default_per_page` but if I'm not mistaken the purpose of this option is different and it accepts an integer instead of an array.
