### ISSUE TITLE
Custom Filter Empty Summary

### ISSUE THREAD

**Issue by marino-mrc** [activeadmin/activeadmin#6887]
Hi,
I'm using activeadmin with custom filters:

`
filter :pratica_filter, label: "Pratica Contiene", as: :select, collection: TipoPratica.all.sort_by{|t| t.descrizione.capitalize }.map{|t| [t.descrizione.capitalize, t.id] }
...
def self.pratica_filter(value)
		# My query here...
end

def self.ransackable_scopes(_auth_object = nil)
		%i[pratica_filter]
end
`
It works but the problem is that I see an empty summary like this (even if the filter is active):

![Screenshot from 2021-04-06 12-04-36](https://user-images.githubusercontent.com/1167190/113695261-f56f2d00-96d0-11eb-9b28-885be8b2a0eb.png)

Please note that "Nessuno" in English means "Nobody, no one".

What I'm doing wrong? It seems that activeadmin doesn't understand the name of the filter and its value in the summary.
Any help will be highly appreciated.
Thank you,
Marco

**Comment by deivid-rodriguez** [comment]
Hi Marco. I have no idea why activeadmin would say there's no active filters when your filter is active. Could you provide a sample application where this problem can be reproduced? Thanks!

**Comment by inveterateliterate** [comment]
I have encountered this same issue. Looking at the source code, and when I log out assigns[:search] in `ActiveAdmin::Filters::ActiveSidebar`, my ransack results for each of my custom filter and my standard attribute filter come in different formats:
```
Ransack::Search<class: Donation, scope: {"calendar_year_eq"=>"2020"}, base: Grouping <conditions: [Condition <attributes: ["region"], predicate: eq, values: ["3"]>], combinator: and>>
```

Where `calendar_year_eq` is the custom filter defined per OP's description above, You can see it doesn't get included in the bas: Grouping object, which has the `conditions` key. 

Thus, `active_filters = ActiveAdmin::Filters::Active.new(active_admin_config, assigns[:search])` only returns a `filters` attribute with length of one, only for the `region` filter because in that class:

```
def initialize(resource, search)
        @resource = resource
        @filters = build_filters(search.conditions)
      end

      private

      def build_filters(conditions)
        conditions.map { |condition| ActiveFilter.new(resource, condition.dup) }
      end
```

the calendar_year_eq doesn't have a `conditions` attribute


Perhaps the `ActiveAdmin::Filters::ActiveSidebar` needs to take into account scopes outside of the base: Grouping object?
