### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by vfonic** [activeadmin/activeadmin#6937]
Repro steps:

1. Go to: https://activeadmin.info/
2. Scroll down and click on "Check Out the Live Demo"

Expected:
Loads demo site

Actual:
Loads heroku error page: Website is offline

**Comment by gregbell** [comment]
Looks like our Heroku stack is EOL. Oops. I just logged into the Heroku UI and upgraded it. It requires a deploy which I'm trying to do now. Ref: https://github.com/activeadmin/demo.activeadmin.info/commit/dc136872422e1f709b6c5421aad63e32e65d9896

**Comment by gregbell** [comment]
Hmmm... looks like I don't have access to the Heroku app running at demo.activeadmin.info. @activeadmin/maintainers any one know? I'm assuming it's the same problem as the version I have in my Heroku account. Someone will need to click the upgrade button in the UI then trigger a deploy.

**Comment by timoschilling** [comment]
Sometime ago we started a new app because we are not able to update the old one. @deivid-rodriguez can you take a look

**Comment by deivid-rodriguez** [comment]
Hi @gregbell :wave: :wave:

Yes, we decided to create a new heroku application because we needed some permissions which only you had and I was not able to get in touch with you. Happy to add you to the new application, or maybe even better to delete the new heroku application and go back to yours.

Regarding the site being down, I temporarily stopped it because it was running into several errors and I didn't have time to investigate what was going on. I'll try to get it back online this week.

**Comment by fabn** [comment]
Demo site is still down, it would be useful to have it back... Thanks.

**Comment by lunaisnotaboy** [comment]
@fabn I know I'm probably not helping, but there's an instance at https://activeadmin-demo-2.herokuapp.com that I set up a few days ago so I could play around with it.

Hope that help!

**Comment by varyonic** [comment]
The (original?) deployment is running at https://demo-activeadmin.herokuapp.com/ 
demo.activeadmin.info is aliased elsewhere, which is not working.

**Comment by deivid-rodriguez** [comment]
Since apologies for the delay, the demo site should be up again.
