### ISSUE TITLE
Using components (e.g. attributes table) in partials

### ISSUE THREAD

**Issue by damrbaby** [activeadmin/activeadmin#725]
I am trying to generate an attributes table that is shared across multiple views, and put it in a partial.  This works fine, except that it is getting rendered twice: once where it is supposed to be rendered, and another just after the body tag of the HTML document.

I'm assuming this is an issue with Arbre. Does anybody have any ideas on what is causing this bug?

Example code (in the ActiveAdmin.register block):

``` ruby
show do
  panel "User Details" do
    render "details"
  end
end
```

In app/views/admin/users/_details.html.haml:

``` ruby
= attributes_table_for user, :first_name, :last_name
```

**Comment by dkniffin** [comment]
Sorry to comment on such an old issue, but I wanted to mention that while the `.arb` solution mostly works, the Arbre partial does not receive `context` by default.

That means you won't be able to do things like `attributes_table`. Instead, you'll have to either pass the resource and do `attributes_table_for(resource)` or pass the context and do `instance_eval` like mentioned above.

I'd love to know if there's a better solution to this. I kind of like @dmfrancisco's solution, because it does the `instance_eval` for you, but you'd still need to pass `context: self` into the `render` call, I think.

**Comment by risinglf** [comment]
Hello, 

I would like to know the best approach, in 2024, for reusing code within custom _ActiveAdmin_ pages, such as a `dashboard`.


I mean if I wish to frequently call a `*.arb` partial from a custom page (for example _dashboard.rb_), would I still need to pass the `context` and invoke `context.instance_eval do` inside the `*.arb` file?

Thanks a lot for your time and support.

**Comment by itkin** [comment]
> I don't know if there are any news about this issue, but I ended up creating a new template handler (under `initializers/extensions/active_admin_template_handler.rb` like this:
> 
> ```ruby
> module ActiveAdmin
>   class CustomTemplateHandler
>     def call(template)
>       <<-END
>       Arbre::Context.new(assigns, self) {
>         context.instance_eval do
>           #{ template.source }
>         end
>       }.to_s
>       END
>     end
>   end
> end
> 
> ActionView::Template.register_template_handler :aa, ActiveAdmin::CustomTemplateHandler.new
> ```
> 
> Then in the `app/views/admin/posts/_show.html.aa` partial I can do:
> 
> ```ruby
> panel "hello" do
>   h2 "world"
> end
> ```

for an unknow reason to me, the above solution doesn't seem to work anymore for partials rendered inside fields_for when i tried to upgrade from rails 5.2 to rails 6.1
