### ISSUE TITLE
Editing/Removing Action Items?

### ISSUE THREAD

**Issue by jonbuda** [activeadmin/activeadmin#760]
I know it's possible to add new action_items to a specified resource/action, but is it possible to remove or disable certain action_items in the header? 

For example, maybe Admin Users shouldn't be able to add a certain resource from the admin because they're always added from the public side of the site, or perhaps Admin Users should never be able to delete some resources.

Couldn't find any simple way to do this looking through the docs and the code.

any ideas? or is this a new feature?

**Comment by VijayBlogVault** [comment]
action_item :only => [:show, :edit] do
       link_to 'Link', link_path(resource) if resource.show?
end

**Comment by mattheworres** [comment]
I'm more than likely in a very small minority, but in my project, when using Pundit (instead of Cancan), ActiveAdmin automatically hides or shows certain action links according to the Pundit policy I define for a given resource.

In my case, I wanted to disable Delete links on resources if it was pointed to via other objects (foreign keys) - the database constraint would fail and in production the user got an empty message which isn't helpful at all. Hiding the links and buttons from both index and show was what I needed. Update the resource policy for `destroy?` and we're in business.

I can imagine ActiveAdmin would work similarly depending on how Cancan allows you to specify resource-specific rules.
