### ISSUE TITLE
activeadmin scope how to i18n

### ISSUE THREAD

**Issue by claf1314** [activeadmin/activeadmin#7612]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/5753378/185727168-c0d41fb0-168d-4139-9f34-31c3f0fc247b.png">
How to customize the scope name.

**Comment by deivid-rodriguez** [comment]
Hi, the current team of maintainers does not have time to answer usage questions like this. Please reach out to Stackoverflow where a wider community can help you, ok? https://stackoverflow.com/questions/tagged/activeadmin. If you find out that this is not possible due to lack of features in ActiveAdmin, please reopen this ticket and we'll try to figure it out! Thanks!
