### ISSUE TITLE
Ransack 4 support

### ISSUE THREAD

**Issue by kivanio** [activeadmin/activeadmin#7809]
Allow Ransack 4 to be used

**Breaking Changes**
[SECURITY] Require explict allowlisting of attributes and associations
https://github.com/activerecord-hackery/ransack/blob/main/CHANGELOG.md#400---2023-02-09

**Comment by gap777** [comment]
I'm also blocked from upgrading my ransack gem b/c of AA

**Comment by javierjulio** [comment]
Thank you. Yes I believe that breaking change might be major for ActiveAdmin users. Since @deivid-rodriguez worked on it, he may be able to provide more info here. I'm not sure yet what we'll do but if it is breaking for ActiveAdmin users, perhaps we have to cut a new major release allowing Ransack v4. Let's see.

**Comment by gap777** [comment]
I don't think AA has to require v4 of `ransack`... it just has to allow it... so I don't think you need to worry about an upgrade of AA causing FORCING an upgrade of ransack and thus FORCING a breaking change. 

The need here is to allow the AA search/filters to work with either ransack 3 or 4. 

I can help if you can direct.

**Comment by chi-block** [comment]
Blocked this as well. Any updates?

**Comment by nlsrchtr** [comment]
Ransack in version 3.2.1 is failing with `undefined method `table_name' for #<Arel::Table` on Rails master, which leads me to this issue. After removing AA from my project and updateing Ransack to version 4, everything is working fine again.

So I assume, this will block the usage of ActiveAdmin with the upcoming Rails release, since Arel::Table had changes, ransack 3.2.1 was not aware of, but ransack 4.0 is.

**Comment by nlsrchtr** [comment]
I published an AA fork with Ransack 4 support [here](https://github.com/nlsrchtr/activeadmin/tree/enable-ransack-in-version-4). After defining `ransackable_attributes` and `ransackable_associations` in the models, it works as expected.

Hope this helps someone else as well.

**Comment by gap777** [comment]
@javierjulio @deivid-rodriguez Any update on this? If AA is not going to work with Rails 7, it'd be very helpful to know ASAP so we can start mitigating (and switching from AA to another admin package).

**Comment by rafthedeveloper** [comment]
Also blocked by this, would be helpful to get some updates here!

**Comment by Fire-Dragon-DoL** [comment]
> @javierjulio @deivid-rodriguez Any update on this? If AA is not going to work with Rails 7, it'd be very helpful to know ASAP so we can start mitigating (and switching from AA to another admin package).

I have been using AA on Rails 7 in production for months. Ransack version 3.2.1

**Comment by Fire-Dragon-DoL** [comment]
> I don't think AA has to require v4 of `ransack`... it just has to allow it... so I don't think you need to worry about an upgrade of AA causing FORCING an upgrade of ransack and thus FORCING a breaking change.
> 
> The need here is to allow the AA search/filters to work with either ransack 3 or 4.
> 
> I can help if you can direct.
> 
> I think you'd need to sense which version gets pulled in, and then provide the `ransackable_attributes` on your the AA models should v4 be used.

I think it still needs a new major version.
Bundle update would break apps if ransack was unlocked, which suggests either way that it is a major version change

**Comment by javierjulio** [comment]
@Fire-Dragon-DoL thank you, I appreciate that. Needed calling out. Same as you I've been running Rails 7 after a recent update with Ransack 3 so this isn't a blocking change for updating from Rails 6 to 7.

After review, I agree that this should be addressed in a major release. Primarily because of the ActiveAdmin Comments module. Further, I don't think it's worth supporting Ransack 3 and 4 so I'd rather do a major release of ActiveAdmin that requires Ransack v4 and another breaking Ransack change.

**Comment by Skulli** [comment]
Is there a possibility to disable that `ransackable_attributes` feature? I am using AA with over 50 models. To define the attributes in every model just to prevent 1-2 attributes seems way too much work for me.

**Comment by Fire-Dragon-DoL** [comment]
> Is there a possibility to disable that `ransackable_attributes` feature? I am using AA with over 50 models. To define the attributes in every model just to prevent 1-2 attributes seems way too much work for me.

You could easily implement something on applicationrecord that allows all of them

**Comment by tindron** [comment]
> > Is there a possibility to disable that `ransackable_attributes` feature? I am using AA with over 50 models. To define the attributes in every model just to prevent 1-2 attributes seems way too much work for me.
> 
> You could easily implement something on applicationrecord that allows all of them

Yeah, here's what mine looks like:
```ruby
  def self.ransackable_associations(_) = reflections.keys
  def self.ransackable_attributes(_) = attribute_names - %w[token]
```
