### ISSUE TITLE
Wrong weekday in frontend for a date

### ISSUE THREAD

**Issue by Piioo** [activeadmin/activeadmin#8015]
### Did you find a bug?

The frontend shows for a long date the wrong weekday in german.
`config.localize_format = :long`

<img width="921" alt="Bildschirmfoto 2023-07-13 um 10 11 23" src="https://github.com/activeadmin/activeadmin/assets/4640423/3d162370-bb32-42a9-b907-8e39195eed9e">
<img width="346" alt="Bildschirmfoto 2023-07-13 um 10 12 04" src="https://github.com/activeadmin/activeadmin/assets/4640423/de686ba5-87e3-40f1-82d9-21fc0348683e">
<img width="270" alt="Bildschirmfoto 2023-07-13 um 10 12 13" src="https://github.com/activeadmin/activeadmin/assets/4640423/9efe45e9-06e8-4534-bde9-6a4c1712cac0">

I cant say, if this happen in english too.

### Expected behavior

In this example the 2022-08-10 is a Wednesday, the frontend should show german "Mittwoch"

### Actual behavior

In this example the 2022-08-10 is a Wednesday but the frontend shows Thursday (Donnerstag)

### How to reproduce

show a `column :created_at` in Frontend in German. 

[our bug report template]: https://github.com/activeadmin/activeadmin/blob/master/tasks/bug_report_template.rb

**Comment by javierjulio** [comment]
Thank you. There isn't anything actionable here since there are too many unknowns about your setup. If you can replicate with our bug report template script so it's isolated to just ActiveAdmin that will help. I would accept a fix if there is an issue in the library but I wonder if this is a user issue. We had another issue reported about German locale recently in #7981 but was closed because of no reproduction. Thanks.
