### ISSUE TITLE
v4 beta 3: Kaminari translation override may affect the host application

### ISSUE THREAD

**Issue by tagliala** [activeadmin/activeadmin#8215]
Not sure that this should be part of activeadmin's `locale.yml` as it is

Kaminari may be used also in the "host" application, so this will override translations of the host front-end

https://github.com/activeadmin/activeadmin/blob/4318a7a5ca1845e08437e8c0d0321ea659b6aa08/config/locales/en.yml#L2-L5

Introduced in 9999e80cadaf16a8d1d0a6e092229107979f5760

**Comment by javierjulio** [comment]
@tagliala yes, that makes sense. Would you like to create a PR and move the `previous` and `next` keys to be under the `active_admin.pagination` key and update the two Kaminari templates to use that instead? We would need to make the same change in the French (FR) and Dutch (NL) locales since they were recently updated.

**Comment by tagliala** [comment]
Will do that
