### ISSUE TITLE
v4 beta 3: External CDNs do not play well with CSP and may be a problem for intranet apps

### ISSUE THREAD

**Issue by tagliala** [activeadmin/activeadmin#8216]
After upgrading to v4 beta, there is an issue with CORS

<img width="798" alt="image" src="https://github.com/activeadmin/activeadmin/assets/556268/fe5e048e-7a0f-4ab7-8231-29dcccc0482f">

I understand that this should be fixed at application level, but I wonder why if it is better to add rails-ujs as a dependency in package.json and pin it from node_modules, instead of relying on a third-party CDN by default

https://github.com/activeadmin/activeadmin/blob/4318a7a5ca1845e08437e8c0d0321ea659b6aa08/config/importmap.rb#L3

**Comment by javierjulio** [comment]
Several problems here. Others have had the same reaction but importmap-rails has made it clear to not pin from `node_modules` directory. We should be able to resolve this for Rails 7.1 since it includes rails-ujs in ESM format but earlier versions don't by updating our Importmap config to pin that file directly. For earlier Rails versions though I don't know what to do. I'd like to vendor the file but from my testing I can't get the pin to override the default rails-ujs lookup so meaning on Rails 7.0, it will retrieve a non-ESM gem-bundled version.

**Comment by javierjulio** [comment]
@tagliala when I started this I was going off of the importmap-rails docs that were incorrect and later updated. That was causing me some grief with this since I did try vendoring the file which I think is best. I've tried again after seeing that recent docs change earlier this week and pinning the `@rails/ujs` to a vendor file now does work and uses the file provided rather than what is bundled in the Rails gem. I'll have an update for that.
