### ISSUE TITLE
Importmap is optional, but raise error if it is not installed.

### ISSUE THREAD

**Issue by martinGerez** [activeadmin/activeadmin#8298]
I've installed ActiveAdmin v4.0.0.beta5, but fails on app execution with the error:
```
uninitialized constant #<Class:ActiveAdmin>::Importmap
``` 
That comes from `lib/active_admin.rb`.

Digging into that file, I've noticed that the requirement of 'importmap-rails' is optional: 

```
begin
  require "importmap-rails"
rescue LoadError
  # importmap-rails is optional
end
```

But still fails when trying to load and instantiate `Importmap.new`.

Currently, we are using Rails 7.0, with Esbuild + Propshaft.

**Comment by javierjulio** [comment]
@martinGerez where is the error coming from? Is it coming from the `_html_head.html.erb` partial? I can't think of anywhere else it would be. Please include more information when submitting an issue.

The expectation is if you aren't using importmap-rails, that you need to update that partial to work with ESBuild and Propshaft. I went with ESBuild at first so it does work but switched to importmap-rails later on. Although I haven't tried Propshaft before.

I would be open to a PR to guard against the usage in the `_html_head.html.erb` partial but otherwise this is expected behavior if you aren't going to use importmap-rails. That's why the partials are copied to your project so you can modify to use different asset management gems. Thank you.

**Comment by Fire-Dragon-DoL** [comment]
What files should I import to make activeadmin work properly, given that I use jsbundling-rails instead of importmap?

**Comment by javierjulio** [comment]
You'll have to install the NPM package and use the JS files from there. It should be very similar with sprockets to what you'd do on v3. It's been awhile since I don't recall offhand, sorry. I'll see if I can dig up what I had originally.

**Comment by Fire-Dragon-DoL** [comment]
> You'll have to install the NPM package and use the JS files from there. It should be very similar with sprockets to what you'd do on v3. It's been awhile since I don't recall offhand, sorry. I'll see if I can dig up what I had originally.

Ok thank you.
For simplicity, I might use importmap. If ActiveAdmin doesn't plan to update the npm package and want to stick to importmap, it might be worth making it required rather than optional.

**Comment by javierjulio** [comment]
The NPM package is updated and has its own beta releases. There aren't any missing.

This what I used in the test app before switching to importmap-rails.

- https://github.com/activeadmin/activeadmin/pull/8186/files#diff-66e300ea248c9f320d5910cd0e62da7e598c6a514a9dfc1e043d3b0a15500b66
- https://github.com/activeadmin/activeadmin/pull/8186/files#diff-a97bb939db845f104d92ab3d20a8df2fee5c0436f132bfd3ea6e3c240776f6ca
- https://github.com/activeadmin/activeadmin/pull/8186/files#diff-1eb8817d043dd28c75a256aa028374f9a4ff0975340933691ba0f65c791613a4

I think most of us on the team prefer jsbundling-rails but was easier to use importmap-rails from an app template perspective and has Rails engine support which were the main reasons I switched. Both approaches are supported though. We need help in documenting them and others since there are multiple asset bundling gems now.

**Comment by Fire-Dragon-DoL** [comment]
> The NPM package is updated and has its own beta releases. There aren't any missing.
> 
> This what I used in the test app before switching to importmap-rails.
> 
> * https://github.com/activeadmin/activeadmin/pull/8186/files#diff-66e300ea248c9f320d5910cd0e62da7e598c6a514a9dfc1e043d3b0a15500b66
> * https://github.com/activeadmin/activeadmin/pull/8186/files#diff-a97bb939db845f104d92ab3d20a8df2fee5c0436f132bfd3ea6e3c240776f6ca
> * https://github.com/activeadmin/activeadmin/pull/8186/files#diff-1eb8817d043dd28c75a256aa028374f9a4ff0975340933691ba0f65c791613a4
> 
> I think most of us on the team prefer jsbundling-rails but was easier to use importmap-rails from an app template perspective and has Rails engine support which were the main reasons I switched. Both approaches are supported though. We need help in documenting them and others since there are multiple asset bundling gems now.

Thank you. I could help documenting once I figure this out. I'm writing a "toy website" from scratch, so I'm going through the experience of installing activeadmin from scratch.

**Comment by Fire-Dragon-DoL** [comment]
I wrote down the following notes:

- Installing activeadmin for usage with `jsbundling-rails`, `cssbundling-rails`, `esbuild` and `tailwind` #activeadmin #learning
	- Add new package.json script `"build:active_admin:css": "tailwindcss -c tailwind-active_admin.config.js -i ./app/assets/stylesheets/active_admin.tailwind.css -o ./app/assets/builds/active_admin.css --minify"`
		- Add to procfile `yarn build:active_admin:css --watch`
	- Add activeadmin dependency to package.json `"@activeadmin/activeadmin": "4.0.0-beta11"`
	- create `app/assets/javascript/active_admin.js`
		-
		  ```js
		  import "flowbite"
		  import "@activeadmin/activeadmin"
		  ```
	- `rails g active_admin:views` and edit `app/views/active_admin/_html_head.html.erb`
		- Add at the top
			-
			  ```erb
			  <%= stylesheet_link_tag "active_admin", "data-turbo-track": "reload" %>
			  ```
		- Add at the bottom
			-
			  ```erb
			  <%= javascript_include_tag "active_admin", "data-turbo-track": "reload", type: "module" %>
			  ```
		- Delete the following line
			-
			  ```erb
			  <%= javascript_importmap_tags "active_admin", importmap: ActiveAdmin.importmap %>
			  ```

![image](https://github.com/user-attachments/assets/c86a5044-5f13-4f94-8594-94e42972643f)

**Comment by estebanutz** [comment]
@Fire-Dragon-DoL Your solution worked perfectly for my app using jsbundling and cssbundling, except for the first addition to package.json I was getting a missing file error for "active_admin.tailwind.css" which I changed to just "active_admin.css". Thanks!

**Comment by griffero** [comment]
I'm facing the same issue with Rails 7 + Sprockets. Any idea on how to make this work?

**Comment by Verseth** [comment]
My notes for making it work for `jsbundling-rails`, `cssbundling-rails`, `esbuild` and `tailwind` inspired by @Fire-Dragon-DoL 

Add new `package.json` scripts:

```json
"build:admin:css": "npx @tailwindcss/cli -c tailwind-active_admin.config.js -i ./app/assets/stylesheets/active_admin.css -o ./app/assets/builds/active_admin.css --minify",
"build:app:css": "npx @tailwindcss/cli -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --minify",
"build:css": "npm run build:app:css && npm run build:admin:css"
```

Add to `Procfile` new entries:

```
admin_css: npm run build:admin:css -- --watch
app_css: npm run build:app:css -- --watch
```

Add activeadmin dependency to package.json

```json
"@activeadmin/activeadmin": "4.0.0-beta22"
```

Create `app/javascript/active_admin.js`

```js
import "flowbite"
import "@activeadmin/activeadmin"
```

Run `rails g active_admin:views` and edit `app/views/active_admin/_html_head.html.erb`:

Add at the top of the file:

```erb
<%= stylesheet_link_tag "active_admin", "data-turbo-track": "reload" %>
```

Add at the bottom of the file:

```erb
<%= javascript_include_tag "active_admin", "data-turbo-track": "reload", type: "module" %>
```

Delete the following line at the bottom of the file:

```erb
<%= javascript_importmap_tags "active_admin", importmap: ActiveAdmin.importmap %>
```
