### ISSUE TITLE
The sidebar navigation has `aria-hidden="true"` even if it is not hidden

### ISSUE THREAD

**Issue by tagliala** [activeadmin/activeadmin#8337]
### Expected behavior

No warnings

### Actual behavior

![image](https://github.com/activeadmin/activeadmin/assets/556268/e6cd2386-a784-4175-b234-d720fefde7a4)

### How to reproduce

1. Go to https://activeadmin-demo.onrender.com/admin
2. Login
2. Resize window with to >= 1280px so that the sidebar is visible

Run Lighthouse

**Comment by tagliala** [comment]
This is also an issue when the menu is hidden, is there any attribute that we are missing?

https://vitepress.dev/guide/what-is-vitepress is not having this issue

**Comment by javierjulio** [comment]
@tagliala worth noting that we don't know what element is affected here. We do use `aria-hidden="true"` in a few places in the site_header partial but just for SVG icons. I believe [this issue is coming from Flowbite that sets and removes that attribute](https://github.com/search?q=repo%3Athemesberg%2Fflowbite+aria-hidden+language%3ATypeScript&type=code&l=TypeScript). I would suggest testing the component we use here from one of the Flowbite examples and see if the example shows the same issue. If it does, then we should open an issue in Flowbite. Thank you.
