### ISSUE TITLE
Wrong style for inputs in form with a has_many input (4.0.0.beta7)

### ISSUE THREAD

**Issue by jaynetics** [activeadmin/activeadmin#8383]
Adding a `has_many` input anywhere in a form causes all other inputs to be prefixed with a list indicator circle.

### Expected behavior

Other inputs should still look like they do before adding a has_many input.

They should look like so:

<img width="222" alt="Screenshot 2024-06-29 at 11 12 53" src="https://github.com/activeadmin/activeadmin/assets/10758879/83c13d14-0efc-4539-895f-77c21af471e5">

### Actual behavior

<img width="170" alt="Screenshot 2024-06-29 at 11 02 17" src="https://github.com/activeadmin/activeadmin/assets/10758879/111a9f4c-abc3-4e7b-856c-41473df5cb2e">

### How to reproduce

```ruby
form do |f|
  f.input :title
  f.has_many :memberships { |f2| f2.input(:user_id) }
end
```

Workaround:

```ruby
form(html: { style: 'list-style: none;' }) do |f|
```

**Comment by javierjulio** [comment]
@jaynetics sorry, this is not reproducible. Please do not open issues unless you can reproduce with the dev app. Based on your other issue, I think the main concern you have that is consistent in both is you aren't using an `f.inputs do ... end` block to wrap these inputs. You need to do that otherwise invalid HTML is outputted (an `<li>` within the form, not a list), whether its Formatastic at fault or not, I don't know. If you inspect source, you'll see what I mean. Thank you.
