### ISSUE TITLE
Meta tags rendering twice (v3)

### ISSUE THREAD

**Issue by marknuzz** [activeadmin/activeadmin#8485]
### Expected behavior

View html source, 
This should render once assuming `config.meta_tags = { foo: 'bar' }`:
`<meta name="foo" content="bar">` 

### Actual behavior

View html source, 
This renders twice:
`<meta name="foo" content="bar">` 

Additionally, the first one is not preceded by a line break, maybe that is a separate issue though. 

### How to reproduce

Gem versions:
arbre (1.7.0)
activeadmin (3.2.5)
```
ActiveAdmin.setup do |config|
  config.meta_tags = { foo: 'bar' }
  ...
end
```

### Additional Info

Likely source of bug:
https://github.com/activeadmin/activeadmin/blob/v3.2.5/lib/active_admin/views/pages/base.rb#L37-L39

If I change this: `text_node(meta(name: name, content: content))`
to this: `meta(name: name, content: content)`,
then only a single meta tag renders, instead of two.

**Comment by javierjulio** [comment]
@marknuzz thank you. This bug has been there a long time actually. 

The fix is as you suggested since it's being used as an Arbre element, it does not need `text_node`, which is why it renders correctly for you with the update. This is one of the gotchas when using and switching between Arbre and Rails tag helpers.

The previous implementation would have been fine if it were scoped with `helpers.tag(:meta, ...)` instead but that approach would still need `text_node` as it's using a Rails tag helper.

We'll accept a PR to fix this. Please open a PR against the 3-0-stable branch. Thank you.
